-- =====================================================
-- Arizona (AZ) Medical Malpractice Rules
-- Enhanced Verification Protocol v2.0
-- =====================================================
-- State: Arizona
-- Governing Law: ARS § 12-561 et seq. (Medical Malpractice Actions)
-- Negligence Model: PURE COMPARATIVE FAULT (ARS § 12-2505)
-- SOL: 2 years from discovery (ARS § 12-542)
-- Damage Caps: NONE — Arizona Constitution Art. 18 § 6 prohibits caps on damages
-- Certificate of Merit: Preliminary expert affidavit REQUIRED at filing (ARS § 12-2603)
-- =====================================================

-- RULE 1: STANDARD OF CARE
INSERT INTO leverage.validation_rules (rule_name, validator_level, validator_name, validator_type, practice_area, specialization, document_type, jurisdiction_scope, jurisdiction_state, validator_config, severity, review_status, is_active, is_template, created_at, updated_at)
VALUES ('AZ-MED-MAL-STANDARD-OF-CARE', 5, 'AZ Medical Malpractice: Standard of Care (ARS § 12-563)', 'content_check', 'personal_injury', 'medical_malpractice', 'complaint', 'state', 'AZ',
    jsonb_build_object('sub_specialization_type', 'medical_malpractice', 'authority_level', 'contextual_rule', 'statute', 'ARS § 12-563', 'standard_text', 'Healthcare provider must use the same care, skill, and treatment that a reasonably prudent healthcare provider would use in the same or similar circumstances', 'key_elements', jsonb_build_array('Duty: provider-patient relationship established', 'Breach: care fell below applicable standard', 'Causation: breach was proximate cause of injury', 'Damages: actual compensable harm'), 'national_standard', 'Arizona uses a national standard of care (not locality rule) — what reasonably prudent provider anywhere would do in same circumstances', 'res_ipsa', 'Available in limited circumstances (e.g., instrument left in body, wrong limb operated on)', 'informed_consent', 'Separate actionable claim under ARS § 12-562; provider must disclose risks a reasonably prudent patient in that position would want to know', 'definition_providers', 'Medical malpractice providers include physicians, nurses, hospitals, nursing homes, and other licensed healthcare entities (ARS § 12-561)', 'verification', jsonb_build_object('statute_verified', true, 'sources', jsonb_build_array('ARS § 12-563', 'ARS § 12-561', 'ARS § 12-562', 'Justia — Arizona Medical Malpractice'), 'confidence', 'high')),
    'error', 'document_verified', true, false, NOW(), NOW())
ON CONFLICT (rule_name) DO UPDATE SET validator_config = EXCLUDED.validator_config, updated_at = NOW();

-- RULE 2: CERTIFICATE OF MERIT / EXPERT WITNESS
INSERT INTO leverage.validation_rules (rule_name, validator_level, validator_name, validator_type, practice_area, specialization, document_type, jurisdiction_scope, jurisdiction_state, validator_config, severity, review_status, is_active, is_template, created_at, updated_at)
VALUES ('AZ-MED-MAL-CERTIFICATE-OF-MERIT', 5, 'AZ Medical Malpractice: Certificate of Merit Required at Filing (ARS § 12-2603)', 'content_check', 'personal_injury', 'medical_malpractice', 'complaint', 'state', 'AZ',
    jsonb_build_object('sub_specialization_type', 'medical_malpractice', 'authority_level', 'contextual_rule', 'statute', 'ARS § 12-2603', 'requirement', 'MANDATORY — Plaintiff must file a preliminary expert opinion affidavit (certificate of merit) along with or within 60 days of the complaint', 'affidavit_contents', jsonb_build_object('expert_qualifications', 'Expert must be licensed in same or related field as defendant', 'opinion', 'Expert must opine that there is a reasonable probability that the defendant failed to meet the standard of care and this failure caused the harm', 'specificity', 'Affidavit must specifically state the conduct believed to be a violation of the standard of care'), 'timing', 'Must be filed within 60 days of complaint unless good cause shown for extension', 'failure_to_file', 'Failure to file certificate of merit is grounds for dismissal of the action', 'expert_qualifications', 'Expert providing certificate must be licensed in same specialty as defendant AND actively practicing in that specialty', 'separate_from_trial_expert', 'Certifying expert may or may not be same person who testifies at trial', 'verification', jsonb_build_object('statute_verified', true, 'sources', jsonb_build_array('ARS § 12-2603', 'Arizona Legislature', 'Seisinger v. Siebel, 220 Ariz. 85 (2009)'), 'confidence', 'high')),
    'error', 'document_verified', true, false, NOW(), NOW())
ON CONFLICT (rule_name) DO UPDATE SET validator_config = EXCLUDED.validator_config, updated_at = NOW();

-- RULE 3: NO DAMAGE CAPS
INSERT INTO leverage.validation_rules (rule_name, validator_level, validator_name, validator_type, practice_area, specialization, document_type, jurisdiction_scope, jurisdiction_state, validator_config, severity, review_status, is_active, is_template, created_at, updated_at)
VALUES ('AZ-MED-MAL-NO-DAMAGE-CAPS', 5, 'AZ Medical Malpractice: NO Damage Caps (AZ Const. Art. 18 § 6)', 'content_check', 'personal_injury', 'medical_malpractice', 'complaint', 'state', 'AZ',
    jsonb_build_object('sub_specialization_type', 'medical_malpractice', 'authority_level', 'contextual_rule', 'constitutional_provision', 'Arizona Constitution Art. 18 § 6', 'economic_damages', 'UNCAPPED — full recovery of all verifiable economic losses (medical bills, lost wages, future care)', 'non_economic_damages', jsonb_build_object('cap_status', 'NO CAP — Arizona Constitution explicitly prohibits any limitation on damages', 'constitutional_text', 'Art. 18 § 6: The right of action to recover damages for injuries shall never be abrogated, and the amount recovered shall not be subject to any statutory limitation'), 'punitive_damages', jsonb_build_object('available', true, 'standard', 'Defendant acted with an evil mind (intentional, malicious, or consciously disregarding substantial risk of harm to others)', 'key_case', 'Rawlings v. Apodaca, 151 Ariz. 149 (1986) — established evil mind standard'), 'collateral_source', 'Arizona allows reduction of damages by collateral source payments in some circumstances', 'significant_note', 'Arizona is one of the few states with NO cap on non-economic damages in medical malpractice — full jury determination of damages', 'verification', jsonb_build_object('statute_verified', true, 'sources', jsonb_build_array('Arizona Constitution Art. 18 § 6', 'Boswell v. Phoenix Newspapers, 152 Ariz. 9 (1986)', 'Justia — Arizona Medical Malpractice'), 'confidence', 'high')),
    'error', 'document_verified', true, false, NOW(), NOW())
ON CONFLICT (rule_name) DO UPDATE SET validator_config = EXCLUDED.validator_config, updated_at = NOW();

-- RULE 4: STATUTE OF LIMITATIONS
INSERT INTO leverage.validation_rules (rule_name, validator_level, validator_name, validator_type, practice_area, specialization, document_type, jurisdiction_scope, jurisdiction_state, validator_config, severity, review_status, is_active, is_template, created_at, updated_at)
VALUES ('AZ-MED-MAL-SOL-2-YEARS', 5, 'AZ Medical Malpractice: 2-Year SOL from Discovery (ARS § 12-542)', 'content_check', 'personal_injury', 'medical_malpractice', 'complaint', 'state', 'AZ',
    jsonb_build_object('sub_specialization_type', 'medical_malpractice', 'authority_level', 'contextual_rule', 'statute', 'ARS § 12-542(1)', 'sol_period', '2 years', 'accrual', 'SOL begins when plaintiff knew or reasonably should have known of the injury and its connection to the medical care — discovery rule', 'statute_text', 'ARS § 12-542(1): Actions for injuries done to the person of another...must be commenced and prosecuted within two years after the cause of action accrues', 'foreign_object', 'Foreign object left in body: 2 years from reasonable discovery; no separate rule required — discovery rule handles it', 'minors', 'For minors: SOL does not begin until minor turns 18 (age of majority), then 2 years', 'mental_incapacity', 'SOL tolled during any period of unsound mind', 'defendant_outside_state', 'SOL tolled while defendant is outside Arizona', 'no_repose', 'Arizona does NOT have a separate statute of repose for medical malpractice claims', 'tolling', jsonb_build_array('Minority (under age 18)', 'Mental incapacity or unsound mind', 'Fraudulent concealment by provider', 'Defendant outside the state'), 'practical_examples', jsonb_build_array('Malpractice Jan 1 2024 discovered same day → File by Jan 1 2026', 'Malpractice Jan 1 2022 discovered Jan 1 2024 → File by Jan 1 2026'), 'verification', jsonb_build_object('statute_verified', true, 'sources', jsonb_build_array('ARS § 12-542(1)', 'Arizona Legislature', 'Gust, Rosenfeld & Henderson v. Prudential Ins. Co., 182 Ariz. 586 (1995)'), 'confidence', 'high')),
    'error', 'document_verified', true, false, NOW(), NOW())
ON CONFLICT (rule_name) DO UPDATE SET validator_config = EXCLUDED.validator_config, updated_at = NOW();

-- RULE 5: PURE COMPARATIVE FAULT
INSERT INTO leverage.validation_rules (rule_name, validator_level, validator_name, validator_type, practice_area, specialization, document_type, jurisdiction_scope, jurisdiction_state, validator_config, severity, review_status, is_active, is_template, created_at, updated_at)
VALUES ('AZ-MED-MAL-PURE-COMPARATIVE-FAULT', 5, 'AZ Medical Malpractice: Pure Comparative Fault (ARS § 12-2505)', 'content_check', 'personal_injury', 'medical_malpractice', 'complaint', 'state', 'AZ',
    jsonb_build_object('sub_specialization_type', 'medical_malpractice', 'authority_level', 'contextual_rule', 'statute', 'ARS § 12-2505', 'negligence_model', 'pure_comparative_fault', 'rule', 'Plaintiff can recover even if more than 50% at fault; damages reduced by plaintiff fault percentage — no bar at any fault level', 'patient_contributory_conduct', 'Patient failure to follow medical orders, provide accurate history, or seek timely care can reduce recovery proportionally', 'assumption_of_risk', 'Replaced by comparative fault principles; voluntary assumption of risk reduces recovery rather than bars it', 'several_only_liability', jsonb_build_object('rule', 'Arizona abolished joint and several liability for non-intentional torts; each defendant liable only for their proportionate share', 'exception', 'Intentional torts: joint and several liability may apply'), 'practical_examples', jsonb_build_array('Plaintiff 0% at fault: Full recovery', 'Plaintiff 30% at fault: Recovery reduced by 30%', 'Plaintiff 70% at fault: Recovery reduced by 70% — can still recover 30%'), 'verification', jsonb_build_object('statute_verified', true, 'sources', jsonb_build_array('ARS § 12-2505', 'Arizona Legislature', 'Wareing v. Falk, 182 Ariz. 495 (App. 1995)'), 'confidence', 'high')),
    'error', 'document_verified', true, false, NOW(), NOW())
ON CONFLICT (rule_name) DO UPDATE SET validator_config = EXCLUDED.validator_config, updated_at = NOW();
