-- =====================================================
-- Alabama (AL) Medical Malpractice Rules
-- Enhanced Verification Protocol v2.0
-- =====================================================
-- State: Alabama
-- Governing Law: Alabama Medical Liability Act of 1987 (Ala. Code § 6-5-480 et seq.)
-- Negligence Model: CONTRIBUTORY NEGLIGENCE (complete bar — one of 4 remaining states)
-- SOL: 2 years (Ala. Code § 6-5-482); 4-year statute of repose
-- Damage Caps: § 6-5-544 cap struck down as unconstitutional; NO effective non-economic cap
-- Expert: Same specialty, licensed and practicing in year preceding malpractice (§ 6-5-548)
-- =====================================================

-- RULE 1: STANDARD OF CARE
INSERT INTO leverage.validation_rules (rule_name, validator_level, validator_name, validator_type, practice_area, specialization, document_type, jurisdiction_scope, jurisdiction_state, validator_config, severity, review_status, is_active, is_template, created_at, updated_at)
VALUES ('AL-MED-MAL-STANDARD-OF-CARE', 5, 'AL Medical Malpractice: Standard of Care (Ala. Code § 6-5-484)', 'content_check', 'personal_injury', 'medical_malpractice', 'complaint', 'state', 'AL',
    jsonb_build_object('sub_specialization_type', 'medical_malpractice', 'authority_level', 'contextual_rule', 'statute', 'Ala. Code § 6-5-484', 'standard_text', 'The standard of care is that degree of care, skill, and diligence used by similarly situated health care providers in the same general neighborhood', 'key_elements', jsonb_build_array('Duty: provider-patient relationship established', 'Breach: failure to meet standard of care in same community', 'Causation: breach proximately caused plaintiff injury', 'Damages: actual injury/harm resulted'), 'locality_rule', 'Alabama applies a same-general-neighborhood/community standard — a modified locality rule', 'res_ipsa', 'Doctrine of res ipsa loquitur available in limited circumstances (e.g., foreign object left in body)', 'informed_consent', 'Separate theory of recovery; provider must disclose material risks a reasonable patient would want to know', 'verification', jsonb_build_object('statute_verified', true, 'sources', jsonb_build_array('Ala. Code § 6-5-484', 'Alabama Medical Liability Act of 1987', 'Justia — Alabama Medical Liability'), 'confidence', 'high')),
    'error', 'document_verified', true, false, NOW(), NOW())
ON CONFLICT (rule_name) DO UPDATE SET validator_config = EXCLUDED.validator_config, updated_at = NOW();

-- RULE 2: EXPERT WITNESS REQUIREMENTS
INSERT INTO leverage.validation_rules (rule_name, validator_level, validator_name, validator_type, practice_area, specialization, document_type, jurisdiction_scope, jurisdiction_state, validator_config, severity, review_status, is_active, is_template, created_at, updated_at)
VALUES ('AL-MED-MAL-EXPERT-WITNESS', 5, 'AL Medical Malpractice: Expert Witness Requirements (Ala. Code § 6-5-548)', 'content_check', 'personal_injury', 'medical_malpractice', 'complaint', 'state', 'AL',
    jsonb_build_object('sub_specialization_type', 'medical_malpractice', 'authority_level', 'contextual_rule', 'statute', 'Ala. Code § 6-5-548', 'requirement', 'Expert testimony required to establish standard of care and breach in almost all medical malpractice cases', 'qualifications', jsonb_build_object('same_specialty', 'Expert must be licensed and practicing in same specialty as defendant at time of alleged malpractice', 'recent_practice', 'Must have practiced in that specialty within one year preceding the alleged malpractice', 'same_type_practice', 'Must be same general type of practice as defendant (e.g., specialist vs. general practitioner matters)'), 'contingent_fee_prohibition', 'Expert whose compensation is contingent on outcome is disqualified (Ala. Code § 6-5-548(e))', 'exception', 'Common knowledge exception: expert not required when negligence is within common knowledge of laypersons (e.g., operating on wrong body part)', 'verification', jsonb_build_object('statute_verified', true, 'sources', jsonb_build_array('Ala. Code § 6-5-548', 'Alabama Medical Liability Act § 6-5-548', 'Cain v. Howorth, 877 So.2d 566 (Ala. 2003)'), 'confidence', 'high')),
    'error', 'document_verified', true, false, NOW(), NOW())
ON CONFLICT (rule_name) DO UPDATE SET validator_config = EXCLUDED.validator_config, updated_at = NOW();

-- RULE 3: DAMAGE CAPS
INSERT INTO leverage.validation_rules (rule_name, validator_level, validator_name, validator_type, practice_area, specialization, document_type, jurisdiction_scope, jurisdiction_state, validator_config, severity, review_status, is_active, is_template, created_at, updated_at)
VALUES ('AL-MED-MAL-DAMAGE-CAPS', 5, 'AL Medical Malpractice: Damage Caps — § 6-5-544 Non-Economic Cap Struck Down', 'content_check', 'personal_injury', 'medical_malpractice', 'complaint', 'state', 'AL',
    jsonb_build_object('sub_specialization_type', 'medical_malpractice', 'authority_level', 'contextual_rule', 'economic_damages', 'UNCAPPED — full recovery of medical expenses, lost wages, future care costs', 'non_economic_damages', jsonb_build_object('cap_status', 'NO EFFECTIVE CAP — original § 6-5-544 cap struck down as unconstitutional', 'original_statute', 'Ala. Code § 6-5-544 originally imposed a cap on non-economic damages', 'constitutional_issue', 'Alabama Supreme Court has held that damage caps violate the right to trial by jury under Ala. Const. Art. I § 11'), 'future_damages', 'Future damages exceeding $150,000 must be paid by periodic payments rather than lump sum (Ala. Code § 6-5-543)', 'punitive_damages', jsonb_build_object('available', true, 'standard', 'Clear and convincing evidence of oppression, fraud, wantonness, or malice', 'cap', 'Capped at greater of $500,000 or 3x compensatory damages (Ala. Code § 6-11-21)'), 'collateral_source_rule', 'Alabama allows defendants to introduce evidence of collateral source payments (Ala. Code § 6-5-545)', 'verification', jsonb_build_object('sources', jsonb_build_array('Ala. Code § 6-5-543', 'Ala. Code § 6-5-544 (struck down)', 'Ala. Code § 6-11-21', 'Alabama Medical Liability Act'), 'confidence', 'high')),
    'error', 'document_verified', true, false, NOW(), NOW())
ON CONFLICT (rule_name) DO UPDATE SET validator_config = EXCLUDED.validator_config, updated_at = NOW();

-- RULE 4: STATUTE OF LIMITATIONS
INSERT INTO leverage.validation_rules (rule_name, validator_level, validator_name, validator_type, practice_area, specialization, document_type, jurisdiction_scope, jurisdiction_state, validator_config, severity, review_status, is_active, is_template, created_at, updated_at)
VALUES ('AL-MED-MAL-SOL-2-YEARS', 5, 'AL Medical Malpractice: 2-Year SOL with 4-Year Repose (Ala. Code § 6-5-482)', 'content_check', 'personal_injury', 'medical_malpractice', 'complaint', 'state', 'AL',
    jsonb_build_object('sub_specialization_type', 'medical_malpractice', 'authority_level', 'contextual_rule', 'statute', 'Ala. Code § 6-5-482', 'sol_period', '2 years', 'statute_text', 'Ala. Code § 6-5-482(a): All actions against physicians, surgeons...shall be commenced within two years next after the act, omission, or failure complained of', 'discovery_rule', 'If injury not discoverable within 2 years: SOL is 6 months from date of discovery, but NEVER beyond 4-year repose', 'statute_of_repose', jsonb_build_object('period', '4 years', 'description', 'ABSOLUTE DEADLINE — no action can be filed more than 4 years after the act of malpractice regardless of discovery', 'statute', 'Ala. Code § 6-5-482(b)'), 'minors', 'For children under 4: SOL runs until child''s 8th birthday or 2 years from act, whichever is later', 'foreign_object', 'Foreign object left in body: discovery rule applies; 6 months from discovery', 'tolling', jsonb_build_array('Minority (under 4 years old — special rule)', 'Mental incapacity', 'Fraudulent concealment'), 'practical_examples', jsonb_build_array('Malpractice Jan 1 2024 → Must file by Jan 1 2026 (2-yr SOL)', 'Malpractice Jan 1 2024 → Absolute deadline Jan 1 2028 (4-yr repose)'), 'verification', jsonb_build_object('statute_verified', true, 'sources', jsonb_build_array('Ala. Code § 6-5-482', 'Alabama Legislature', 'Justia — Alabama Medical Liability Act'), 'confidence', 'high')),
    'error', 'document_verified', true, false, NOW(), NOW())
ON CONFLICT (rule_name) DO UPDATE SET validator_config = EXCLUDED.validator_config, updated_at = NOW();

-- RULE 5: CONTRIBUTORY NEGLIGENCE (COMPLETE BAR)
INSERT INTO leverage.validation_rules (rule_name, validator_level, validator_name, validator_type, practice_area, specialization, document_type, jurisdiction_scope, jurisdiction_state, validator_config, severity, review_status, is_active, is_template, created_at, updated_at)
VALUES ('AL-MED-MAL-CONTRIBUTORY-NEGLIGENCE', 5, 'AL Medical Malpractice: Contributory Negligence — COMPLETE BAR (Common Law)', 'content_check', 'personal_injury', 'medical_malpractice', 'complaint', 'state', 'AL',
    jsonb_build_object('sub_specialization_type', 'medical_malpractice', 'authority_level', 'contextual_rule', 'negligence_model', 'contributory_negligence', 'complete_bar', 'Alabama applies pure contributory negligence — ANY fault by plaintiff bars ALL recovery in medical malpractice cases', 'harshness', 'Alabama is one of only 4 remaining contributory negligence states — harshest rule against plaintiffs', 'patient_non_compliance', 'Patient failure to follow medical instructions can constitute contributory negligence barring recovery', 'assumption_of_risk', 'Separate defense: patient who assumes known medical risk may be barred', 'last_clear_chance', 'Last clear chance doctrine recognized as exception: if provider had last clear chance to avoid harm, plaintiff may still recover despite contributory negligence', 'practical_impact', jsonb_build_object('plaintiff_0_fault', 'Full recovery available', 'plaintiff_1_percent_fault', 'NO RECOVERY — complete bar', 'plaintiff_50_percent_fault', 'NO RECOVERY — complete bar'), 'verification', jsonb_build_object('common_law_verified', true, 'sources', jsonb_build_array('Alabama contributory negligence doctrine', 'Alabama Medical Liability Act', 'Berner v. Caldwell, 543 So.2d 686 (Ala. 1989)'), 'confidence', 'high')),
    'error', 'document_verified', true, false, NOW(), NOW())
ON CONFLICT (rule_name) DO UPDATE SET validator_config = EXCLUDED.validator_config, updated_at = NOW();
