-- =====================================================
-- Delaware (DE) Medical Malpractice Rules
-- Enhanced Verification Protocol v2.0
-- =====================================================
-- State: Delaware
-- Governing Law: 18 Del. C. § 6801 et seq. (Health-Care Medical Negligence)
-- Negligence Model: MODIFIED COMPARATIVE FAULT — 51% bar (10 Del. C. § 8132)
-- SOL: 2 years from injury; 3 years if not discoverable (18 Del. C. § 6856)
-- Damage Caps: No specific non-economic cap in Delaware
-- Affidavit of Merit: MANDATORY — must accompany complaint (18 Del. C. § 6853)
-- =====================================================

-- RULE 1: STANDARD OF CARE
INSERT INTO leverage.validation_rules (rule_name, validator_level, validator_name, validator_type, practice_area, specialization, document_type, jurisdiction_scope, jurisdiction_state, validator_config, severity, review_status, is_active, is_template, created_at, updated_at)
VALUES ('DE-MED-MAL-STANDARD-OF-CARE', 5, 'DE Medical Malpractice: Standard of Care (18 Del. C. § 6801)', 'content_check', 'personal_injury', 'medical_malpractice', 'complaint', 'state', 'DE',
    jsonb_build_object('sub_specialization_type', 'medical_malpractice', 'authority_level', 'contextual_rule', 'statute', '18 Del. C. § 6801', 'standard_text', 'A healthcare provider must exercise the degree of care, skill, and treatment which, in the light of all relevant surrounding circumstances, is recognized as acceptable and appropriate by reasonably skilled practitioners in the same field of health care', 'key_elements', jsonb_build_array('Duty: provider-patient relationship established', 'Breach: deviation from applicable standard of care', 'Causation: breach was proximate cause of harm', 'Damages: actual injury or damages resulted'), 'national_standard', 'Delaware applies a national standard of care — what is recognized as acceptable by reasonably skilled practitioners in the same specialty', 'res_ipsa', 'Available in limited circumstances (foreign object in body, surgery on wrong body part)', 'informed_consent', 'Separate theory: provider must disclose risks that a reasonable patient would consider material to treatment decision (18 Del. C. § 6801)', 'hospital_liability', 'Hospitals may be liable for negligent credentialing, direct institutional negligence, and vicarious liability for employees', 'scotus_note', 'SCOTUS ruled in Berk v. Choy (Jan 2026): Delaware affidavit requirement does NOT apply in federal court under diversity jurisdiction — state court requirement unchanged', 'verification', jsonb_build_object('statute_verified', true, 'sources', jsonb_build_array('18 Del. C. § 6801', 'Delaware Code Title 18 Ch. 68', 'Justia — Delaware Medical Negligence'), 'confidence', 'high')),
    'error', 'document_verified', true, false, NOW(), NOW())
ON CONFLICT (rule_name) DO UPDATE SET validator_config = EXCLUDED.validator_config, updated_at = NOW();

-- RULE 2: AFFIDAVIT OF MERIT (MANDATORY)
INSERT INTO leverage.validation_rules (rule_name, validator_level, validator_name, validator_type, practice_area, specialization, document_type, jurisdiction_scope, jurisdiction_state, validator_config, severity, review_status, is_active, is_template, created_at, updated_at)
VALUES ('DE-MED-MAL-AFFIDAVIT-OF-MERIT', 5, 'DE Medical Malpractice: Affidavit of Merit MANDATORY (18 Del. C. § 6853)', 'content_check', 'personal_injury', 'medical_malpractice', 'complaint', 'state', 'DE',
    jsonb_build_object('sub_specialization_type', 'medical_malpractice', 'authority_level', 'contextual_rule', 'statute', '18 Del. C. § 6853', 'requirement', 'MANDATORY — A complaint for medical negligence must be accompanied by an affidavit of merit signed by a qualified expert witness', 'affidavit_contents', jsonb_build_object('expert_cv', 'Must include expert''s curriculum vitae', 'opinion', 'Expert must confirm there are reasonable grounds to believe the standard of care was breached and the breach caused the plaintiff''s injuries', 'confidentiality', 'Affidavit filed in sealed envelope — not discoverable and cannot be used as evidence in the action'), 'expert_qualifications', jsonb_build_object('licensed', 'Expert must be licensed in same or similar specialty as defendant', 'relevant_experience', 'Must have clinical experience related to the care at issue', 'active_practice', 'Must be actively practicing or recently retired'), 'timing_extension', '60-day extension available if plaintiff demonstrates good cause (e.g., difficulty obtaining medical records)', 'failure_to_file', 'Court will refuse to file a complaint without the required affidavit of merit', 'federal_court_exception', 'SCOTUS Berk v. Choy (Jan 2026): Affidavit not required in federal court under diversity jurisdiction', 'verification', jsonb_build_object('statute_verified', true, 'sources', jsonb_build_array('18 Del. C. § 6853', 'Delaware Code Title 18 Ch. 68', 'Berk v. Choy, U.S. Supreme Court (Jan 2026)'), 'confidence', 'high')),
    'error', 'document_verified', true, false, NOW(), NOW())
ON CONFLICT (rule_name) DO UPDATE SET validator_config = EXCLUDED.validator_config, updated_at = NOW();

-- RULE 3: DAMAGE CAPS
INSERT INTO leverage.validation_rules (rule_name, validator_level, validator_name, validator_type, practice_area, specialization, document_type, jurisdiction_scope, jurisdiction_state, validator_config, severity, review_status, is_active, is_template, created_at, updated_at)
VALUES ('DE-MED-MAL-DAMAGE-CAPS', 5, 'DE Medical Malpractice: No Statutory Non-Economic Cap; Punitive Limits Apply', 'content_check', 'personal_injury', 'medical_malpractice', 'complaint', 'state', 'DE',
    jsonb_build_object('sub_specialization_type', 'medical_malpractice', 'authority_level', 'contextual_rule', 'economic_damages', 'UNCAPPED — full recovery of all verifiable economic losses (medical bills, lost wages, future care)', 'non_economic_damages', jsonb_build_object('cap_status', 'NO statutory cap on non-economic damages in Delaware medical malpractice cases', 'full_jury_determination', 'Jury has full discretion to award non-economic damages'), 'punitive_damages', jsonb_build_object('availability', 'Available for outrageous, willful, or wanton conduct', 'standard', 'Must show malice or conscious disregard for plaintiff rights', 'approach', 'Delaware courts exercise oversight on punitive awards to prevent grossly excessive amounts'), 'collateral_source', 'Delaware applies modified collateral source rule — jury may be informed of certain collateral source payments', 'periodic_payments', 'Court may order periodic payments for future damages in medical negligence cases', 'verification', jsonb_build_object('sources', jsonb_build_array('18 Del. C. § 6801 et seq.', 'Delaware Code Title 18 Ch. 68', 'Justia — Delaware Medical Negligence'), 'confidence', 'high')),
    'error', 'document_verified', true, false, NOW(), NOW())
ON CONFLICT (rule_name) DO UPDATE SET validator_config = EXCLUDED.validator_config, updated_at = NOW();

-- RULE 4: STATUTE OF LIMITATIONS
INSERT INTO leverage.validation_rules (rule_name, validator_level, validator_name, validator_type, practice_area, specialization, document_type, jurisdiction_scope, jurisdiction_state, validator_config, severity, review_status, is_active, is_template, created_at, updated_at)
VALUES ('DE-MED-MAL-SOL-2-YEARS', 5, 'DE Medical Malpractice: 2-Year SOL; 3-Year if Not Discoverable (18 Del. C. § 6856)', 'content_check', 'personal_injury', 'medical_malpractice', 'complaint', 'state', 'DE',
    jsonb_build_object('sub_specialization_type', 'medical_malpractice', 'authority_level', 'contextual_rule', 'statute', '18 Del. C. § 6856', 'sol_period', '2 years', 'accrual', 'SOL begins from the date of the injury', 'discovery_extension', 'If injury was unknown and could not have been discovered with reasonable diligence within 2 years: claim may be filed within 3 years from the date of injury', 'statute_text', '18 Del. C. § 6856: A health-care medical negligence action must be brought within 2 years from date of negligent act, except that if injury was unknown and could not have been discovered with reasonable diligence within the 2-year period, the action may be filed within 3 years of the negligent act', 'sexual_abuse_exception', 'For sexual abuse of a patient by a healthcare provider: NO statute of limitations — claim may be filed at any time', 'minors', 'For children under 6: SOL does not begin until child''s 6th birthday (or standard 2/3-year period, whichever is longer)', 'tolling', jsonb_build_array('Minority (under age 6 — special extension to 6th birthday)', 'Mental incapacity', 'Fraudulent concealment', 'Sexual abuse (no time limit)'), 'practical_examples', jsonb_build_array('Malpractice Jan 1 2024 discovered same day → File by Jan 1 2026', 'Malpractice Jan 1 2024 not discoverable until Jan 1 2026 → Must still file by Jan 1 2027 (3-yr outside limit)'), 'verification', jsonb_build_object('statute_verified', true, 'sources', jsonb_build_array('18 Del. C. § 6856', 'Delaware Code Title 18 Ch. 68', 'Justia — Delaware Medical Negligence'), 'confidence', 'high')),
    'error', 'document_verified', true, false, NOW(), NOW())
ON CONFLICT (rule_name) DO UPDATE SET validator_config = EXCLUDED.validator_config, updated_at = NOW();

-- RULE 5: MODIFIED COMPARATIVE FAULT (51% BAR)
INSERT INTO leverage.validation_rules (rule_name, validator_level, validator_name, validator_type, practice_area, specialization, document_type, jurisdiction_scope, jurisdiction_state, validator_config, severity, review_status, is_active, is_template, created_at, updated_at)
VALUES ('DE-MED-MAL-MODIFIED-COMPARATIVE', 5, 'DE Medical Malpractice: Modified Comparative Fault 51% Bar (10 Del. C. § 8132)', 'content_check', 'personal_injury', 'medical_malpractice', 'complaint', 'state', 'DE',
    jsonb_build_object('sub_specialization_type', 'medical_malpractice', 'authority_level', 'contextual_rule', 'statute', '10 Del. C. § 8132', 'negligence_model', 'modified_comparative_51_bar', 'rule', 'Plaintiff may recover if their contributory negligence is 50% or LESS; barred if contributory negligence exceeds 50% (51% or more)', 'patient_non_compliance', 'Patient failure to follow medical instructions, provide accurate medical history, or delay seeking care can reduce or bar recovery', 'joint_several_liability', jsonb_build_object('rule', 'Delaware retains modified joint and several liability; defendants responsible for their proportionate share', 'statute', '10 Del. C. § 8132'), 'practical_examples', jsonb_build_array('Plaintiff 0% fault: Full recovery', 'Plaintiff 30% fault: Recovery reduced by 30%', 'Plaintiff 50% fault: Recovery reduced by 50% — can still recover', 'Plaintiff 51% fault: NO RECOVERY'), 'verification', jsonb_build_object('statute_verified', true, 'sources', jsonb_build_array('10 Del. C. § 8132', 'Delaware Legislature', 'Justia — Delaware Comparative Fault'), 'confidence', 'high')),
    'error', 'document_verified', true, false, NOW(), NOW())
ON CONFLICT (rule_name) DO UPDATE SET validator_config = EXCLUDED.validator_config, updated_at = NOW();
