-- =====================================================
-- Alaska (AK) Medical Malpractice Rules
-- Enhanced Verification Protocol v2.0
-- =====================================================
-- State: Alaska
-- Governing Law: AS 09.55.536 et seq. (Medical Malpractice Actions)
-- Negligence Model: PURE COMPARATIVE FAULT (AS 09.17.060)
-- SOL: 2 years from discovery (AS 09.55.560(a))
-- Non-economic Damage Cap: $250,000 standard; $400,000 for wrongful death or >70% disability (AS 09.55.549)
-- Expert: Required per AS 09.55.540
-- =====================================================

-- RULE 1: STANDARD OF CARE
INSERT INTO leverage.validation_rules (rule_name, validator_level, validator_name, validator_type, practice_area, specialization, document_type, jurisdiction_scope, jurisdiction_state, validator_config, severity, review_status, is_active, is_template, created_at, updated_at)
VALUES ('AK-MED-MAL-STANDARD-OF-CARE', 5, 'AK Medical Malpractice: Standard of Care (AS 09.55.540)', 'content_check', 'personal_injury', 'medical_malpractice', 'complaint', 'state', 'AK',
    jsonb_build_object('sub_specialization_type', 'medical_malpractice', 'authority_level', 'contextual_rule', 'statute', 'AS 09.55.540', 'standard_text', 'Provider must exercise the degree of care, skill, and treatment that a reasonably competent provider in the same field would use under same or similar circumstances', 'key_elements', jsonb_build_array('Duty: provider-patient relationship established', 'Breach: failure to meet standard of care', 'Causation: breach proximately caused injury', 'Damages: measurable harm resulted'), 'national_standard', 'Alaska generally applies a national/statewide standard of care rather than a strict locality rule', 'res_ipsa', 'Available where negligence is obvious without expert testimony (e.g., surgical instrument left in body)', 'informed_consent', 'Separate claim: provider must disclose risks a reasonably prudent patient would find material to treatment decision', 'voluntary_arbitration', 'Parties may agree to arbitrate medical malpractice disputes (AS 09.55.535); not mandatory', 'verification', jsonb_build_object('statute_verified', true, 'sources', jsonb_build_array('AS 09.55.540', 'Alaska Statutes Title 9 Ch. 55', 'Justia — Alaska Medical Malpractice'), 'confidence', 'high')),
    'error', 'document_verified', true, false, NOW(), NOW())
ON CONFLICT (rule_name) DO UPDATE SET validator_config = EXCLUDED.validator_config, updated_at = NOW();

-- RULE 2: EXPERT WITNESS REQUIREMENTS
INSERT INTO leverage.validation_rules (rule_name, validator_level, validator_name, validator_type, practice_area, specialization, document_type, jurisdiction_scope, jurisdiction_state, validator_config, severity, review_status, is_active, is_template, created_at, updated_at)
VALUES ('AK-MED-MAL-EXPERT-WITNESS', 5, 'AK Medical Malpractice: Expert Witness Requirements (AS 09.55.540)', 'content_check', 'personal_injury', 'medical_malpractice', 'complaint', 'state', 'AK',
    jsonb_build_object('sub_specialization_type', 'medical_malpractice', 'authority_level', 'contextual_rule', 'statute', 'AS 09.55.540', 'requirement', 'Expert testimony required to prove standard of care and its breach in virtually all medical malpractice cases', 'qualifications', jsonb_build_object('licensed', 'Must be licensed healthcare provider in same or similar specialty', 'active_practice', 'Must be actively practicing or recently retired from same type of practice', 'familiarity', 'Must demonstrate familiarity with standard of care applicable in Alaska'), 'advisory_panel', 'Court may convene an expert advisory panel to evaluate the claim before trial (AS 09.55.536)', 'contingent_fee', 'No express prohibition but contingent expert fee arrangements discouraged under professional standards', 'common_knowledge_exception', 'Expert not required when negligence is within common knowledge of laypersons', 'verification', jsonb_build_object('statute_verified', true, 'sources', jsonb_build_array('AS 09.55.540', 'AS 09.55.536', 'Alaska Rules of Evidence Rule 702'), 'confidence', 'high')),
    'error', 'document_verified', true, false, NOW(), NOW())
ON CONFLICT (rule_name) DO UPDATE SET validator_config = EXCLUDED.validator_config, updated_at = NOW();

-- RULE 3: DAMAGE CAPS
INSERT INTO leverage.validation_rules (rule_name, validator_level, validator_name, validator_type, practice_area, specialization, document_type, jurisdiction_scope, jurisdiction_state, validator_config, severity, review_status, is_active, is_template, created_at, updated_at)
VALUES ('AK-MED-MAL-DAMAGE-CAPS', 5, 'AK Medical Malpractice: Non-Economic Damage Cap $250K/$400K (AS 09.55.549)', 'content_check', 'personal_injury', 'medical_malpractice', 'complaint', 'state', 'AK',
    jsonb_build_object('sub_specialization_type', 'medical_malpractice', 'authority_level', 'contextual_rule', 'statute', 'AS 09.55.549', 'economic_damages', 'UNCAPPED — full recovery of all verifiable monetary losses (medical expenses, lost wages, future care)', 'non_economic_damages', jsonb_build_object('standard_cap', '$250,000 — applies to most personal injury medical malpractice cases', 'elevated_cap', '$400,000 — applies when: (1) wrongful death results, OR (2) injury causes permanent impairment of more than 70%', 'cap_per_provider', 'Cap applies regardless of the number of healthcare providers involved', 'exception', 'Cap does NOT apply if injury resulted from reckless or intentional misconduct by provider'), 'hedonic_damages', 'Excluded from non-economic damages under AS 09.55.549 — no separate recovery for loss of enjoyment of life', 'punitive_damages', jsonb_build_object('available', true, 'standard', 'Clear and convincing evidence of outrageous conduct, malice, or reckless indifference', 'cap', 'Greater of 3x compensatory damages or $500,000 (AS 09.17.020)'), 'periodic_payments', 'Future damages may be ordered as periodic payments at defendant request (AS 09.17.040)', 'verification', jsonb_build_object('statute_verified', true, 'sources', jsonb_build_array('AS 09.55.549', 'AS 09.17.020', 'AS 09.17.040', 'Alaska Statutes Title 9', 'NCSL Medical Malpractice State Summary'), 'confidence', 'high')),
    'error', 'document_verified', true, false, NOW(), NOW())
ON CONFLICT (rule_name) DO UPDATE SET validator_config = EXCLUDED.validator_config, updated_at = NOW();

-- RULE 4: STATUTE OF LIMITATIONS
INSERT INTO leverage.validation_rules (rule_name, validator_level, validator_name, validator_type, practice_area, specialization, document_type, jurisdiction_scope, jurisdiction_state, validator_config, severity, review_status, is_active, is_template, created_at, updated_at)
VALUES ('AK-MED-MAL-SOL-2-YEARS', 5, 'AK Medical Malpractice: 2-Year SOL from Discovery (AS 09.55.560)', 'content_check', 'personal_injury', 'medical_malpractice', 'complaint', 'state', 'AK',
    jsonb_build_object('sub_specialization_type', 'medical_malpractice', 'authority_level', 'contextual_rule', 'statute', 'AS 09.55.560(a)', 'sol_period', '2 years', 'accrual', 'SOL begins when plaintiff knows or should have known of the injury AND its possible negligent cause (discovery rule applies)', 'statute_text', 'AS 09.55.560(a): No action for injury or death...may be brought more than two years after the plaintiff discovers or reasonably should have discovered the existence of all elements essential to the cause of action', 'foreign_object', 'Foreign object left in body: 2 years from discovery of foreign object', 'minors', 'For minors: SOL tolled until minor reaches majority (age 18), then 2 years', 'tolling', jsonb_build_array('Minority (under age 18)', 'Mental incapacity', 'Fraudulent concealment by provider', 'Continuous treatment doctrine'), 'practical_examples', jsonb_build_array('Malpractice Jan 1 2024 discovered same day → File by Jan 1 2026', 'Malpractice Jan 1 2024 discovered Jan 1 2025 → File by Jan 1 2027'), 'no_repose', 'Alaska does NOT have a separate statute of repose for medical malpractice — only the 2-year discovery rule applies', 'verification', jsonb_build_object('statute_verified', true, 'sources', jsonb_build_array('AS 09.55.560(a)', 'Alaska Legislature', 'Justia — Alaska Medical Malpractice'), 'confidence', 'high')),
    'error', 'document_verified', true, false, NOW(), NOW())
ON CONFLICT (rule_name) DO UPDATE SET validator_config = EXCLUDED.validator_config, updated_at = NOW();

-- RULE 5: PURE COMPARATIVE FAULT
INSERT INTO leverage.validation_rules (rule_name, validator_level, validator_name, validator_type, practice_area, specialization, document_type, jurisdiction_scope, jurisdiction_state, validator_config, severity, review_status, is_active, is_template, created_at, updated_at)
VALUES ('AK-MED-MAL-PURE-COMPARATIVE-FAULT', 5, 'AK Medical Malpractice: Pure Comparative Fault (AS 09.17.060)', 'content_check', 'personal_injury', 'medical_malpractice', 'complaint', 'state', 'AK',
    jsonb_build_object('sub_specialization_type', 'medical_malpractice', 'authority_level', 'contextual_rule', 'statute', 'AS 09.17.060', 'negligence_model', 'pure_comparative_fault', 'rule', 'Plaintiff can recover even if 99% at fault; damages reduced proportionally by plaintiff fault percentage', 'patient_non_compliance', 'Patient failure to follow treatment instructions or disclose relevant medical history can reduce recovery proportionally', 'several_only_liability', jsonb_build_object('rule', 'Alaska abolished joint and several liability; each defendant liable only for their proportionate share (AS 09.17.080)', 'exception', 'Intentional torts: joint and several liability may still apply'), 'practical_examples', jsonb_build_array('Plaintiff 0% at fault: Full recovery of damages', 'Plaintiff 30% at fault: Recovery reduced to 70% of total damages', 'Plaintiff 99% at fault: Recovery of only 1% of total damages'), 'multiple_defendants', 'Each defendant pays only their allocated percentage of fault (proportionate liability)', 'verification', jsonb_build_object('statute_verified', true, 'sources', jsonb_build_array('AS 09.17.060', 'AS 09.17.080', 'Alaska Legislature'), 'confidence', 'high')),
    'error', 'document_verified', true, false, NOW(), NOW())
ON CONFLICT (rule_name) DO UPDATE SET validator_config = EXCLUDED.validator_config, updated_at = NOW();
