-- =====================================================
-- Florida (FL) Medical Malpractice Rules
-- Enhanced Verification Protocol v2.0
-- =====================================================
-- State: Florida
-- Governing Law: Florida Statutes Chapter 766 (Medical Malpractice and Related Matters)
-- Negligence Model: PURE COMPARATIVE FAULT (FS § 768.81)
-- SOL: 2 years from discovery; 4-year statute of repose (FS § 95.11(4)(b))
-- Non-Economic Cap: $750,000 reinstated by 2025 legislation (FS § 766.118); $1.5M for catastrophic
-- Pre-suit: MANDATORY 90-day pre-suit notice + investigation period (FS § 766.106)
-- Expert: Affidavit with pre-suit notice required (FS § 766.102)
-- =====================================================

-- RULE 1: STANDARD OF CARE
INSERT INTO leverage.validation_rules (rule_name, validator_level, validator_name, validator_type, practice_area, specialization, document_type, jurisdiction_scope, jurisdiction_state, validator_config, severity, review_status, is_active, is_template, created_at, updated_at)
VALUES ('FL-MED-MAL-STANDARD-OF-CARE', 5, 'FL Medical Malpractice: Standard of Care (FS § 766.102)', 'content_check', 'personal_injury', 'medical_malpractice', 'complaint', 'state', 'FL',
    jsonb_build_object('sub_specialization_type', 'medical_malpractice', 'authority_level', 'contextual_rule', 'statute', 'FS § 766.102', 'standard_text', 'The prevailing professional standard of care is that level of care, skill, and treatment which, in light of all relevant surrounding circumstances, is recognized as acceptable and appropriate by reasonably prudent similar health care providers', 'key_elements', jsonb_build_array('Duty: provider-patient relationship established', 'Breach: failure to meet prevailing professional standard of care', 'Causation: breach caused or contributed to injury', 'Damages: actual compensable harm'), 'national_standard', 'Florida uses a national standard of care — what is recognized as acceptable by reasonably prudent similar healthcare providers', 'res_ipsa', 'Available (Foreign object left in body is negligence per se under FS § 766.102(3))', 'informed_consent', 'Separate claim under FS § 766.103: provider must disclose material risks; Florida requires written consent forms for many procedures', 'hospital_liability', 'Hospitals may be directly liable and vicariously liable for employed physicians; ostensible agency recognized', 'verification', jsonb_build_object('statute_verified', true, 'sources', jsonb_build_array('FS § 766.102', 'Florida Statutes Chapter 766', 'Justia — Florida Medical Malpractice'), 'confidence', 'high')),
    'error', 'document_verified', true, false, NOW(), NOW())
ON CONFLICT (rule_name) DO UPDATE SET validator_config = EXCLUDED.validator_config, updated_at = NOW();

-- RULE 2: MANDATORY PRE-SUIT PROCESS
INSERT INTO leverage.validation_rules (rule_name, validator_level, validator_name, validator_type, practice_area, specialization, document_type, jurisdiction_scope, jurisdiction_state, validator_config, severity, review_status, is_active, is_template, created_at, updated_at)
VALUES ('FL-MED-MAL-PRE-SUIT-PROCESS', 5, 'FL Medical Malpractice: MANDATORY Pre-Suit Notice and Investigation (FS § 766.106)', 'content_check', 'personal_injury', 'medical_malpractice', 'complaint', 'state', 'FL',
    jsonb_build_object('sub_specialization_type', 'medical_malpractice', 'authority_level', 'contextual_rule', 'statute', 'FS § 766.106', 'requirement', 'MANDATORY — Before filing a lawsuit, plaintiff must serve written notice of intent on all prospective defendants and their liability insurers', 'presuit_notice_contents', jsonb_build_object('who', 'All prospective defendants and their liability insurers', 'what', 'Written notice of intent to initiate litigation, with corroborating verified written medical expert opinion (FS § 766.102)', 'when', 'Must be served before filing complaint'), 'investigation_period', jsonb_build_object('duration', '90 days from notice (can be extended to 120 days by agreement or up to 120 days by court)', 'purpose', 'Allows parties to conduct informal discovery, investigate claim, and attempt settlement', 'activities', 'Both sides may conduct informal investigation; defendant must respond with rejection, offer, or request for additional information'), 'expert_requirement', 'Plaintiff must provide a verified written medical expert opinion with the notice, corroborating the claim (FS § 766.102)', 'sol_tolling', 'SOL tolled during the 90-day pre-suit investigation period', 'failure_to_comply', 'Failure to properly serve pre-suit notice is a fatal defect subject to dismissal', 'verification', jsonb_build_object('statute_verified', true, 'sources', jsonb_build_array('FS § 766.106', 'FS § 766.102', 'Florida Statutes Chapter 766', 'Justia — Florida Medical Malpractice'), 'confidence', 'high')),
    'error', 'document_verified', true, false, NOW(), NOW())
ON CONFLICT (rule_name) DO UPDATE SET validator_config = EXCLUDED.validator_config, updated_at = NOW();

-- RULE 3: DAMAGE CAPS
INSERT INTO leverage.validation_rules (rule_name, validator_level, validator_name, validator_type, practice_area, specialization, document_type, jurisdiction_scope, jurisdiction_state, validator_config, severity, review_status, is_active, is_template, created_at, updated_at)
VALUES ('FL-MED-MAL-DAMAGE-CAPS', 5, 'FL Medical Malpractice: $750K Non-Economic Cap Reinstated 2025 (FS § 766.118)', 'content_check', 'personal_injury', 'medical_malpractice', 'complaint', 'state', 'FL',
    jsonb_build_object('sub_specialization_type', 'medical_malpractice', 'authority_level', 'contextual_rule', 'statute', 'FS § 766.118', 'economic_damages', 'UNCAPPED — full recovery of all verifiable economic losses', 'non_economic_damages', jsonb_build_object('cap_2025', '$750,000 per claimant regardless of number of defendants (effective January 1, 2025)', 'catastrophic_exception', '$1,500,000 cap for cases involving: (1) permanent total disability, (2) severe brain damage, (3) paralysis, or similar catastrophic injuries', 'history', 'Prior caps under FS § 766.118 (2003) were struck down by FL Supreme Court in McCall v. US (2014) as violating equal protection. New 2025 legislation reinstated caps', 'legislation', '2025 legislation effective January 1, 2025 — applies to claims based on acts occurring on or after January 1, 2025'), 'punitive_damages', jsonb_build_object('availability', 'Available for intentional misconduct or gross negligence (FS § 768.72)', 'cap', 'Capped at greater of 3x compensatory damages or $500,000; if intentional misconduct: greater of 4x compensatory or $2M (FS § 768.73)'), 'collateral_source', 'Florida has modified collateral source rule: benefits from employer, government, or insurance may offset damages (FS § 768.76)', 'verification', jsonb_build_object('statute_verified', true, 'sources', jsonb_build_array('FS § 766.118', 'FS § 768.72', 'FS § 768.73', 'FS § 768.76', 'McCall v. United States, 134 So.3d 894 (Fla. 2014)', 'Florida Legislature 2025'), 'confidence', 'high')),
    'error', 'document_verified', true, false, NOW(), NOW())
ON CONFLICT (rule_name) DO UPDATE SET validator_config = EXCLUDED.validator_config, updated_at = NOW();

-- RULE 4: STATUTE OF LIMITATIONS
INSERT INTO leverage.validation_rules (rule_name, validator_level, validator_name, validator_type, practice_area, specialization, document_type, jurisdiction_scope, jurisdiction_state, validator_config, severity, review_status, is_active, is_template, created_at, updated_at)
VALUES ('FL-MED-MAL-SOL-2-YEARS', 5, 'FL Medical Malpractice: 2-Year SOL with 4-Year Repose (FS § 95.11(4)(b))', 'content_check', 'personal_injury', 'medical_malpractice', 'complaint', 'state', 'FL',
    jsonb_build_object('sub_specialization_type', 'medical_malpractice', 'authority_level', 'contextual_rule', 'statute', 'FS § 95.11(4)(b)', 'sol_period', '2 years', 'accrual', 'SOL begins from the time of injury or from when injury was known or should have been known through reasonable diligence', 'statute_of_repose', jsonb_build_object('period', '4 years', 'description', 'ABSOLUTE DEADLINE — no claim after 4 years from date of malpractice regardless of discovery', 'exception', 'Fraudulent concealment: can extend to 7 years'), 'fraud_exception', 'If defendant fraudulently concealed malpractice: SOL may extend to 7 years from date of act', 'foreign_object', 'Foreign object left in body: 2 years from discovery (without 4-year repose application)', 'minors', 'For minors under 8: SOL does not begin until age 8 OR 2 years from injury, whichever is later', 'sol_tolling_presuit', 'SOL is TOLLED during the mandatory 90-day pre-suit investigation period (FS § 766.106)', 'tolling', jsonb_build_array('Pre-suit notice period (90 days)', 'Minority under age 8', 'Fraudulent concealment (extends to 7 years from act)', 'Mental incapacity'), 'practical_examples', jsonb_build_array('Malpractice Jan 1 2024 discovered same day → File by Jan 1 2026 (2-yr SOL; remember 90-day pre-suit first)', 'Malpractice Jan 1 2024 absolute repose → Jan 1 2028 (4-yr repose)'), 'verification', jsonb_build_object('statute_verified', true, 'sources', jsonb_build_array('FS § 95.11(4)(b)', 'FS § 766.106', 'Florida Legislature', 'Justia — Florida Medical Malpractice'), 'confidence', 'high')),
    'error', 'document_verified', true, false, NOW(), NOW())
ON CONFLICT (rule_name) DO UPDATE SET validator_config = EXCLUDED.validator_config, updated_at = NOW();

-- RULE 5: PURE COMPARATIVE FAULT
INSERT INTO leverage.validation_rules (rule_name, validator_level, validator_name, validator_type, practice_area, specialization, document_type, jurisdiction_scope, jurisdiction_state, validator_config, severity, review_status, is_active, is_template, created_at, updated_at)
VALUES ('FL-MED-MAL-PURE-COMPARATIVE-FAULT', 5, 'FL Medical Malpractice: Pure Comparative Fault (FS § 768.81)', 'content_check', 'personal_injury', 'medical_malpractice', 'complaint', 'state', 'FL',
    jsonb_build_object('sub_specialization_type', 'medical_malpractice', 'authority_level', 'contextual_rule', 'statute', 'FS § 768.81', 'negligence_model', 'pure_comparative_fault', 'rule', 'Plaintiff can recover even if 99% at fault; damages reduced proportionally by plaintiff fault percentage — no bar at any level', 'patient_non_compliance', 'Patient failure to follow medical orders, provide accurate history, or seek timely care reduces recovery proportionally', 'joint_several_limitation', jsonb_build_object('rule', 'Florida modified joint and several liability — generally each defendant pays only their proportionate share of non-economic damages', 'economic_damages', 'Joint and several liability remains for defendants with 10% or more fault for economic damages (FS § 768.81)'), 'practical_examples', jsonb_build_array('Plaintiff 0% fault: Full recovery', 'Plaintiff 30% fault: Recovery reduced by 30%', 'Plaintiff 99% fault: Can still recover 1% of damages'), 'verification', jsonb_build_object('statute_verified', true, 'sources', jsonb_build_array('FS § 768.81', 'Florida Legislature', 'Fabre v. Marin, 623 So.2d 1182 (Fla. 1993)'), 'confidence', 'high')),
    'error', 'document_verified', true, false, NOW(), NOW())
ON CONFLICT (rule_name) DO UPDATE SET validator_config = EXCLUDED.validator_config, updated_at = NOW();
