-- =====================================================
-- Colorado (CO) Medical Malpractice Rules
-- Enhanced Verification Protocol v2.0
-- =====================================================
-- State: Colorado
-- Governing Law: Colorado Health Care Availability Act (CRS § 13-64-101 et seq.)
-- Negligence Model: MODIFIED COMPARATIVE FAULT — 50% bar (CRS § 13-21-111)
-- SOL: 2 years (CRS § 13-80-102.5); 3-year statute of repose
-- Non-Economic Cap: $300,000 for acts before Jan 1 2025; $415,000 for 2025 acts (HB24-1472), increasing to $875,000 by 2029
-- Total Cap: Cannot exceed $1M or 125% of non-economic cap (CRS § 13-64-302)
-- Certificate of Review: MANDATORY within 60 days of complaint (CRS § 13-20-602)
-- =====================================================

-- RULE 1: STANDARD OF CARE
INSERT INTO leverage.validation_rules (rule_name, validator_level, validator_name, validator_type, practice_area, specialization, document_type, jurisdiction_scope, jurisdiction_state, validator_config, severity, review_status, is_active, is_template, created_at, updated_at)
VALUES ('CO-MED-MAL-STANDARD-OF-CARE', 5, 'CO Medical Malpractice: Standard of Care (CRS § 13-64-117)', 'content_check', 'personal_injury', 'medical_malpractice', 'complaint', 'state', 'CO',
    jsonb_build_object('sub_specialization_type', 'medical_malpractice', 'authority_level', 'contextual_rule', 'statute', 'CRS § 13-64-117', 'standard_text', 'Healthcare provider must act in accordance with the degree of learning and skill ordinarily possessed and exercised by practitioners in the same field of practice under similar circumstances', 'key_elements', jsonb_build_array('Duty: provider-patient relationship established', 'Breach: care fell below applicable standard', 'Causation: breach was proximate cause of injury', 'Damages: actual compensable harm'), 'national_standard', 'Colorado applies a national standard of care for specialists; general practitioners measured against similarly situated general practitioners', 'res_ipsa', 'Available in limited circumstances where injury would not normally occur absent negligence', 'informed_consent', 'Separate claim: provider must disclose material risks that a reasonable patient would want to know before agreeing to treatment', 'institutional_liability', 'Hospitals may be held directly liable for negligent credentialing and vicariously liable under agency principles', 'verification', jsonb_build_object('statute_verified', true, 'sources', jsonb_build_array('CRS § 13-64-117', 'Colorado Health Care Availability Act', 'Justia — Colorado Medical Malpractice'), 'confidence', 'high')),
    'error', 'document_verified', true, false, NOW(), NOW())
ON CONFLICT (rule_name) DO UPDATE SET validator_config = EXCLUDED.validator_config, updated_at = NOW();

-- RULE 2: CERTIFICATE OF REVIEW
INSERT INTO leverage.validation_rules (rule_name, validator_level, validator_name, validator_type, practice_area, specialization, document_type, jurisdiction_scope, jurisdiction_state, validator_config, severity, review_status, is_active, is_template, created_at, updated_at)
VALUES ('CO-MED-MAL-CERTIFICATE-OF-REVIEW', 5, 'CO Medical Malpractice: Certificate of Review MANDATORY (CRS § 13-20-602)', 'content_check', 'personal_injury', 'medical_malpractice', 'complaint', 'state', 'CO',
    jsonb_build_object('sub_specialization_type', 'medical_malpractice', 'authority_level', 'contextual_rule', 'statute', 'CRS § 13-20-602', 'requirement', 'MANDATORY — Plaintiff must file a Certificate of Review signed by a licensed professional affirming the claim has merit', 'timing', 'Must be filed within 60 days after service of the complaint on the defendant; extensions available for good cause', 'certificate_contents', jsonb_build_object('expert_consultation', 'Plaintiff attorney must consult with a licensed healthcare professional in the same specialty as defendant', 'opinion', 'Consulting expert must conclude that the claim involves reasonable grounds and does not lack substantial justification', 'signature', 'Certificate signed by plaintiff counsel certifying the consultation occurred'), 'failure_to_file', 'Failure to file Certificate of Review within required period is grounds for dismissal of action', 'distinction', 'Colorado Certificate of Review differs from most states — it is counsel certification of consultation, not expert affidavit attached to complaint', 'verification', jsonb_build_object('statute_verified', true, 'sources', jsonb_build_array('CRS § 13-20-602', 'Colorado Legislature', 'Justia — Colorado CRS 13-20-602'), 'confidence', 'high')),
    'error', 'document_verified', true, false, NOW(), NOW())
ON CONFLICT (rule_name) DO UPDATE SET validator_config = EXCLUDED.validator_config, updated_at = NOW();

-- RULE 3: DAMAGE CAPS
INSERT INTO leverage.validation_rules (rule_name, validator_level, validator_name, validator_type, practice_area, specialization, document_type, jurisdiction_scope, jurisdiction_state, validator_config, severity, review_status, is_active, is_template, created_at, updated_at)
VALUES ('CO-MED-MAL-DAMAGE-CAPS', 5, 'CO Medical Malpractice: Non-Economic Cap Increasing $300K→$875K (CRS § 13-64-302, HB24-1472)', 'content_check', 'personal_injury', 'medical_malpractice', 'complaint', 'state', 'CO',
    jsonb_build_object('sub_specialization_type', 'medical_malpractice', 'authority_level', 'contextual_rule', 'statute', 'CRS § 13-64-302', 'economic_damages', 'UNCAPPED — full recovery of all verifiable economic losses', 'non_economic_damages', jsonb_build_object('pre_2025_cap', '$300,000 (acts/omissions before January 1, 2025)', 'cap_2025', '$415,000 (acts/omissions on or after January 1, 2025)', 'cap_schedule', jsonb_build_object('2025', '$415,000', '2026', '$530,000', '2027', '$640,000', '2028', '$755,000', '2029_and_on', '$875,000, then CPI-indexed every 2 years'), 'legislation', 'HB24-1472 signed June 2024, effective January 1, 2025'), 'total_damages_limit', jsonb_build_object('rule', 'Total damages against any one healthcare professional or institution cannot exceed $1,000,000 OR 125% of the non-economic damages cap, whichever is GREATER', 'statute', 'CRS § 13-64-302(1)'), 'wrongful_death', jsonb_build_object('pre_2025', 'Prior cap applicable', 'cap_2025', '$555,000 increasing to $1,575,000 by 2029'), 'punitive_damages', 'Punitive damages generally not available in negligence-only malpractice; available for willful/wanton conduct', 'court_override', 'Court may allow recovery beyond caps in exceptional cases where applying limits would be unfair', 'verification', jsonb_build_object('statute_verified', true, 'sources', jsonb_build_array('CRS § 13-64-302', 'HB24-1472 (2024)', 'Colorado Legislature', 'Wilson Elser — Colorado Caps Update 2024'), 'confidence', 'high')),
    'error', 'document_verified', true, false, NOW(), NOW())
ON CONFLICT (rule_name) DO UPDATE SET validator_config = EXCLUDED.validator_config, updated_at = NOW();

-- RULE 4: STATUTE OF LIMITATIONS
INSERT INTO leverage.validation_rules (rule_name, validator_level, validator_name, validator_type, practice_area, specialization, document_type, jurisdiction_scope, jurisdiction_state, validator_config, severity, review_status, is_active, is_template, created_at, updated_at)
VALUES ('CO-MED-MAL-SOL-2-YEARS', 5, 'CO Medical Malpractice: 2-Year SOL with 3-Year Repose (CRS § 13-80-102.5)', 'content_check', 'personal_injury', 'medical_malpractice', 'complaint', 'state', 'CO',
    jsonb_build_object('sub_specialization_type', 'medical_malpractice', 'authority_level', 'contextual_rule', 'statute', 'CRS § 13-80-102.5', 'sol_period', '2 years', 'accrual', 'SOL begins on the date the claimant discovers or in the exercise of reasonable diligence should have discovered the injury and its probable cause', 'statute_of_repose', jsonb_build_object('period', '3 years', 'description', 'ABSOLUTE DEADLINE — no action can be filed more than 3 years after the act of malpractice regardless of discovery', 'statute', 'CRS § 13-80-102.5(1)'), 'foreign_object', 'Foreign object left in body: discovery rule applies; 2 years from discovery (within 3-year outer repose)', 'minors', 'For minors: SOL tolled until child is 8 years old or 2 years from act, whichever is later (CRS § 13-80-102.5(2))', 'fraudulent_concealment', 'SOL tolled where defendant fraudulently concealed the malpractice', 'tolling', jsonb_build_array('Minority (until age 8)', 'Mental incapacity', 'Fraudulent concealment by provider'), 'practical_examples', jsonb_build_array('Malpractice Jan 1 2024 discovered same day → File by Jan 1 2026', 'Malpractice Jan 1 2024 discovered Jan 1 2026 → Still must file by Jan 1 2027 (3-yr repose)'), 'verification', jsonb_build_object('statute_verified', true, 'sources', jsonb_build_array('CRS § 13-80-102.5', 'Colorado Legislature', 'Justia — Colorado Medical Malpractice'), 'confidence', 'high')),
    'error', 'document_verified', true, false, NOW(), NOW())
ON CONFLICT (rule_name) DO UPDATE SET validator_config = EXCLUDED.validator_config, updated_at = NOW();

-- RULE 5: MODIFIED COMPARATIVE FAULT (50% BAR)
INSERT INTO leverage.validation_rules (rule_name, validator_level, validator_name, validator_type, practice_area, specialization, document_type, jurisdiction_scope, jurisdiction_state, validator_config, severity, review_status, is_active, is_template, created_at, updated_at)
VALUES ('CO-MED-MAL-MODIFIED-COMPARATIVE', 5, 'CO Medical Malpractice: Modified Comparative Fault 50% Bar (CRS § 13-21-111)', 'content_check', 'personal_injury', 'medical_malpractice', 'complaint', 'state', 'CO',
    jsonb_build_object('sub_specialization_type', 'medical_malpractice', 'authority_level', 'contextual_rule', 'statute', 'CRS § 13-21-111', 'negligence_model', 'modified_comparative_50_bar', 'rule', 'Plaintiff may recover if their fault is 50% or LESS; barred from any recovery if fault exceeds 50%', 'patient_non_compliance', 'Patient failure to follow medical instructions, disclose medical history, or seek timely care can be allocated as plaintiff fault reducing or barring recovery', 'several_only_liability', jsonb_build_object('rule', 'Each defendant liable only for their proportionate share of non-economic damages; joint and several only for economic damages for defendants who are more than 50% at fault (CRS § 13-21-111.5)', 'statute', 'CRS § 13-21-111.5'), 'practical_examples', jsonb_build_array('Plaintiff 0% fault: Full recovery', 'Plaintiff 30% fault: Recovery reduced by 30%', 'Plaintiff 50% fault: Recovery reduced by 50% — can still recover', 'Plaintiff 51% fault: NO RECOVERY'), 'verification', jsonb_build_object('statute_verified', true, 'sources', jsonb_build_array('CRS § 13-21-111', 'CRS § 13-21-111.5', 'Colorado Legislature'), 'confidence', 'high')),
    'error', 'document_verified', true, false, NOW(), NOW())
ON CONFLICT (rule_name) DO UPDATE SET validator_config = EXCLUDED.validator_config, updated_at = NOW();
