-- =====================================================
-- Arkansas (AR) Medical Malpractice Rules
-- Enhanced Verification Protocol v2.0
-- =====================================================
-- State: Arkansas
-- Governing Law: Ark. Code § 16-114-201 et seq. (Medical Injury Actions)
-- Negligence Model: MODIFIED COMPARATIVE FAULT — 50% bar (Ark. Code § 16-64-122)
-- SOL: 2 years from act (§ 16-114-203); foreign object: 1 year from discovery
-- Damage Caps: $500,000 non-economic cap (Arkansas Amendment 94, 2018)
-- Expert: Required per Ark. Code § 16-114-207 (Ark. R. Evid. Rule 702)
-- Punitive: Capped at greater of $250,000 or 3x compensatory, max $1M (§ 16-55-208)
-- =====================================================

-- RULE 1: STANDARD OF CARE
INSERT INTO leverage.validation_rules (rule_name, validator_level, validator_name, validator_type, practice_area, specialization, document_type, jurisdiction_scope, jurisdiction_state, validator_config, severity, review_status, is_active, is_template, created_at, updated_at)
VALUES ('AR-MED-MAL-STANDARD-OF-CARE', 5, 'AR Medical Malpractice: Standard of Care (Ark. Code § 16-114-206)', 'content_check', 'personal_injury', 'medical_malpractice', 'complaint', 'state', 'AR',
    jsonb_build_object('sub_specialization_type', 'medical_malpractice', 'authority_level', 'contextual_rule', 'statute', 'Ark. Code § 16-114-206', 'standard_text', 'A medical care provider shall exercise that degree of care, skill, and treatment which, in light of all relevant surrounding circumstances, is recognized as acceptable and appropriate by reasonably careful, qualified medical care providers in the same field', 'key_elements', jsonb_build_array('Duty: provider-patient relationship established', 'Breach: failure to meet the applicable standard of care', 'Causation: breach was proximate cause of plaintiff injury', 'Damages: compensable harm resulted'), 'national_standard', 'Arkansas moved away from strict locality rule to a national/reasonably prudent provider standard', 'res_ipsa', 'Available where the negligence is of a type that a layperson can recognize without expert testimony', 'informed_consent', 'Separate theory under Ark. Code § 16-114-206(b): provider must disclose risks that a reasonably prudent patient would consider material', 'hospital_liability', 'Hospitals may be held vicariously liable for physicians under agency or ostensible agency theories', 'verification', jsonb_build_object('statute_verified', true, 'sources', jsonb_build_array('Ark. Code § 16-114-206', 'Arkansas Medical Malpractice Act', 'Justia — Arkansas Medical Injury'), 'confidence', 'high')),
    'error', 'document_verified', true, false, NOW(), NOW())
ON CONFLICT (rule_name) DO UPDATE SET validator_config = EXCLUDED.validator_config, updated_at = NOW();

-- RULE 2: EXPERT WITNESS REQUIREMENTS
INSERT INTO leverage.validation_rules (rule_name, validator_level, validator_name, validator_type, practice_area, specialization, document_type, jurisdiction_scope, jurisdiction_state, validator_config, severity, review_status, is_active, is_template, created_at, updated_at)
VALUES ('AR-MED-MAL-EXPERT-WITNESS', 5, 'AR Medical Malpractice: Expert Witness Requirements (Ark. Code § 16-114-207)', 'content_check', 'personal_injury', 'medical_malpractice', 'complaint', 'state', 'AR',
    jsonb_build_object('sub_specialization_type', 'medical_malpractice', 'authority_level', 'contextual_rule', 'statute', 'Ark. Code § 16-114-207', 'requirement', 'Expert testimony required to establish standard of care and breach in virtually all Arkansas medical malpractice cases', 'qualifications', jsonb_build_object('rule_702', 'Expert must qualify under Arkansas Rules of Evidence Rule 702 (knowledge, skill, experience, training, or education)', 'same_specialty', 'Generally should be licensed in same or closely related specialty as defendant', 'recent_practice', 'Must be familiar with the standard of care applicable at the time of the alleged malpractice'), 'contingent_fee_prohibition', 'Expert compensation contingent on outcome of case is PROHIBITED (Ark. Code § 16-114-207(b))', 'certificate_of_merit', jsonb_build_object('statute', 'Ark. Code § 16-114-209', 'status', 'Merit affidavit requirement retained but 30-day timing rule was struck as unconstitutional in Summerville v. Thrower (Ark. 2005)', 'current_rule', 'Plaintiff must have a good-faith basis (supported by expert opinion) for claims — no formal pre-filing affidavit currently enforceable'), 'common_knowledge_exception', 'Expert not required when negligence is obvious to laypersons (e.g., amputating wrong limb)', 'verification', jsonb_build_object('statute_verified', true, 'sources', jsonb_build_array('Ark. Code § 16-114-207', 'Ark. R. Evid. Rule 702', 'Summerville v. Thrower, 362 Ark. 416 (2005)'), 'confidence', 'high')),
    'error', 'document_verified', true, false, NOW(), NOW())
ON CONFLICT (rule_name) DO UPDATE SET validator_config = EXCLUDED.validator_config, updated_at = NOW();

-- RULE 3: DAMAGE CAPS
INSERT INTO leverage.validation_rules (rule_name, validator_level, validator_name, validator_type, practice_area, specialization, document_type, jurisdiction_scope, jurisdiction_state, validator_config, severity, review_status, is_active, is_template, created_at, updated_at)
VALUES ('AR-MED-MAL-DAMAGE-CAPS', 5, 'AR Medical Malpractice: $500K Non-Economic Cap (Arkansas Amendment 94)', 'content_check', 'personal_injury', 'medical_malpractice', 'complaint', 'state', 'AR',
    jsonb_build_object('sub_specialization_type', 'medical_malpractice', 'authority_level', 'contextual_rule', 'constitutional_provision', 'Arkansas Constitution Amendment 94 (2018)', 'economic_damages', 'UNCAPPED — full recovery of all verifiable economic losses (medical bills, lost income, future care costs)', 'non_economic_damages', jsonb_build_object('cap_amount', '$500,000', 'cap_basis', 'Arkansas Amendment 94, adopted by voters in November 2018, permits non-economic damage caps for medical injuries', 'applies_to', 'Pain and suffering, mental anguish, loss of consortium, emotional distress, and similar non-economic losses', 'adjustments', 'Cap may be subject to periodic adjustments per enabling legislation'), 'punitive_damages', jsonb_build_object('available', true, 'standard', 'Defendant knew or ought to have known, in light of surrounding circumstances, that conduct would naturally result in injury', 'cap', 'Greater of $250,000 or 3x compensatory damages, maximum $1,000,000 (Ark. Code § 16-55-208)'), 'collateral_source', 'Arkansas modified collateral source rule (Ark. Code § 16-55-212): jury may be informed of collateral source payments to reduce duplicate recovery', 'verification', jsonb_build_object('sources', jsonb_build_array('Arkansas Amendment 94 (2018)', 'Ark. Code § 16-55-208', 'Ark. Code § 16-55-212', 'Justia — Arkansas Medical Injury'), 'confidence', 'high')),
    'error', 'document_verified', true, false, NOW(), NOW())
ON CONFLICT (rule_name) DO UPDATE SET validator_config = EXCLUDED.validator_config, updated_at = NOW();

-- RULE 4: STATUTE OF LIMITATIONS
INSERT INTO leverage.validation_rules (rule_name, validator_level, validator_name, validator_type, practice_area, specialization, document_type, jurisdiction_scope, jurisdiction_state, validator_config, severity, review_status, is_active, is_template, created_at, updated_at)
VALUES ('AR-MED-MAL-SOL-2-YEARS', 5, 'AR Medical Malpractice: 2-Year SOL (Ark. Code § 16-114-203)', 'content_check', 'personal_injury', 'medical_malpractice', 'complaint', 'state', 'AR',
    jsonb_build_object('sub_specialization_type', 'medical_malpractice', 'authority_level', 'contextual_rule', 'statute', 'Ark. Code § 16-114-203', 'sol_period', '2 years', 'accrual', 'SOL begins on date of the wrongful act, omission, or negligence', 'statute_text', 'Ark. Code § 16-114-203(a): No action for medical injury shall be commenced more than two years from the date of the wrongful act complained of', 'foreign_object', 'Foreign object left in body: action may be commenced within 1 year from date object is discovered or should have been discovered (§ 16-114-203(b))', 'minors', 'For children under 9: SOL runs until the later of child''s 11th birthday OR 2 years from wrongful act. If injury not known before 11th birthday: 2 years after discovery or until age 19, whichever first', 'no_repose', 'Arkansas does NOT have a separate absolute statute of repose beyond the SOL provisions', 'tolling', jsonb_build_array('Minority (under 9 — special rule as stated above)', 'Mental incapacity', 'Fraudulent concealment by provider'), 'practical_examples', jsonb_build_array('Malpractice Jan 1 2024 → Must file by Jan 1 2026', 'Foreign object discovered Jan 1 2025 → Must file by Jan 1 2026 (1 year from discovery)'), 'verification', jsonb_build_object('statute_verified', true, 'sources', jsonb_build_array('Ark. Code § 16-114-203', 'Arkansas Legislature', 'Justia — Arkansas Medical Injury'), 'confidence', 'high')),
    'error', 'document_verified', true, false, NOW(), NOW())
ON CONFLICT (rule_name) DO UPDATE SET validator_config = EXCLUDED.validator_config, updated_at = NOW();

-- RULE 5: MODIFIED COMPARATIVE FAULT (50% BAR)
INSERT INTO leverage.validation_rules (rule_name, validator_level, validator_name, validator_type, practice_area, specialization, document_type, jurisdiction_scope, jurisdiction_state, validator_config, severity, review_status, is_active, is_template, created_at, updated_at)
VALUES ('AR-MED-MAL-MODIFIED-COMPARATIVE', 5, 'AR Medical Malpractice: Modified Comparative Fault 50% Bar (Ark. Code § 16-64-122)', 'content_check', 'personal_injury', 'medical_malpractice', 'complaint', 'state', 'AR',
    jsonb_build_object('sub_specialization_type', 'medical_malpractice', 'authority_level', 'contextual_rule', 'statute', 'Ark. Code § 16-64-122', 'negligence_model', 'modified_comparative_50_bar', 'rule', 'Plaintiff may recover if their fault is 50% or LESS; plaintiff is barred if fault exceeds 50%', 'statute_text', 'Ark. Code § 16-64-122: Contributory fault shall not bar recovery if the fault of the person seeking recovery is not greater than the fault of the person from whom recovery is sought', 'patient_non_compliance', 'Patient failure to follow medical instructions, disclose relevant history, or seek timely follow-up can be allocated as plaintiff fault', 'several_only_liability', jsonb_build_object('rule', 'Arkansas abolished joint and several liability; each defendant liable only for their proportionate share', 'statute', 'Ark. Code § 16-55-201'), 'practical_examples', jsonb_build_array('Plaintiff 0% at fault: Full recovery', 'Plaintiff 30% at fault: Recovery reduced by 30%', 'Plaintiff 50% at fault: Recovery reduced by 50% — can still recover', 'Plaintiff 51% at fault: NO RECOVERY — barred'), 'verification', jsonb_build_object('statute_verified', true, 'sources', jsonb_build_array('Ark. Code § 16-64-122', 'Ark. Code § 16-55-201', 'Arkansas Legislature'), 'confidence', 'high')),
    'error', 'document_verified', true, false, NOW(), NOW())
ON CONFLICT (rule_name) DO UPDATE SET validator_config = EXCLUDED.validator_config, updated_at = NOW();
