-- Seed data for leverage.leverage_settlement_windows
-- Estimated settlement timelines by incident_type + state.
-- Drives the nudge system: if a case exceeds estimated_days_to_settle,
-- LEVERAGE prompts the attorney to record settlement details.
-- Source: Industry benchmarks (Martindale-Nolo, ABOTA, insurance industry data)

INSERT INTO leverage.leverage_settlement_windows (incident_type, state, estimated_days_to_settle, p25_days, p75_days, source, notes) VALUES
-- Slip & Fall (Premises Liability) - all 50 states
-- Generally 6-12 months for pre-suit settlement; longer in litigious jurisdictions
('slip_fall', 'AL', 270, 120, 420, 'industry_benchmark', 'Alabama: Contributory negligence means fewer cases settle; those that do settle faster'),
('slip_fall', 'AK', 300, 150, 450, 'industry_benchmark', 'Alaska: Pure comparative; moderate timeline'),
('slip_fall', 'AZ', 240, 120, 360, 'industry_benchmark', 'Arizona: Modified comparative; moderate settlement pace'),
('slip_fall', 'AR', 270, 120, 420, 'industry_benchmark', 'Arkansas: Modified 50% bar'),
('slip_fall', 'CA', 300, 150, 540, 'industry_benchmark', 'California: Pure comparative; high policy limits; longer negotiation typical'),
('slip_fall', 'CO', 240, 120, 360, 'industry_benchmark', 'Colorado: Several liability reduces insurer urgency'),
('slip_fall', 'CT', 270, 120, 420, 'industry_benchmark', 'Connecticut: Modified 51% bar'),
('slip_fall', 'DE', 240, 120, 360, 'industry_benchmark', 'Delaware: Modified 50% bar; smaller state, faster docket'),
('slip_fall', 'FL', 210, 90, 360, 'industry_benchmark', 'Florida: High volume; insurers settle faster post-2023 reform'),
('slip_fall', 'GA', 270, 120, 420, 'industry_benchmark', 'Georgia: Modified 50% bar; Superior Knowledge Rule'),
('slip_fall', 'HI', 300, 150, 450, 'industry_benchmark', 'Hawaii: Island jurisdiction; slower insurer response'),
('slip_fall', 'ID', 240, 120, 360, 'industry_benchmark', 'Idaho: Strict 50% bar'),
('slip_fall', 'IL', 270, 120, 420, 'industry_benchmark', 'Illinois: Modified 51%; Cook County notoriously slow'),
('slip_fall', 'IN', 240, 120, 360, 'industry_benchmark', 'Indiana: Several liability; moderate pace'),
('slip_fall', 'IA', 270, 120, 420, 'industry_benchmark', 'Iowa: Traditional common law approach'),
('slip_fall', 'KS', 240, 120, 360, 'industry_benchmark', 'Kansas: Modified 50% bar'),
('slip_fall', 'KY', 240, 90, 390, 'industry_benchmark', 'Kentucky: Pure comparative; 1-year SOL adds urgency'),
('slip_fall', 'LA', 180, 90, 300, 'industry_benchmark', 'Louisiana: Civil law; 1-year SOL; fastest settlement state'),
('slip_fall', 'ME', 300, 150, 540, 'industry_benchmark', 'Maine: 6-year SOL; no urgency to settle quickly'),
('slip_fall', 'MD', 300, 150, 480, 'industry_benchmark', 'Maryland: Contributory; cases that settle are strong liability'),
('slip_fall', 'MA', 270, 120, 420, 'industry_benchmark', 'Massachusetts: Modified comparative'),
('slip_fall', 'MI', 270, 120, 420, 'industry_benchmark', 'Michigan: Modified comparative; auto threshold'),
('slip_fall', 'MN', 270, 120, 420, 'industry_benchmark', 'Minnesota: Modified 50% bar'),
('slip_fall', 'MS', 300, 150, 480, 'industry_benchmark', 'Mississippi: High jury awards; insurers may delay'),
('slip_fall', 'MO', 270, 120, 420, 'industry_benchmark', 'Missouri: Modified comparative (2021 reform)'),
('slip_fall', 'MT', 300, 150, 450, 'industry_benchmark', 'Montana: Rural jurisdiction; slower insurer response'),
('slip_fall', 'NE', 270, 120, 420, 'industry_benchmark', 'Nebraska: Modified 51%; 4-year SOL'),
('slip_fall', 'NV', 240, 120, 360, 'industry_benchmark', 'Nevada: Modified 51%; fast-growing state'),
('slip_fall', 'NH', 270, 120, 420, 'industry_benchmark', 'New Hampshire: Modified 51%'),
('slip_fall', 'NJ', 300, 150, 480, 'industry_benchmark', 'New Jersey: Mode-of-Operation Rule; busy courts'),
('slip_fall', 'NM', 270, 120, 420, 'industry_benchmark', 'New Mexico: Pure comparative'),
('slip_fall', 'NY', 330, 180, 540, 'industry_benchmark', 'New York: Busy courts; joint and several; longest settlement timelines'),
('slip_fall', 'NC', 300, 150, 480, 'industry_benchmark', 'North Carolina: Contributory; fewer cases proceed to settlement'),
('slip_fall', 'ND', 270, 120, 420, 'industry_benchmark', 'North Dakota: Modified 50%'),
('slip_fall', 'OH', 270, 120, 420, 'industry_benchmark', 'Ohio: Open and obvious doctrine limits premises liability'),
('slip_fall', 'OK', 270, 120, 420, 'industry_benchmark', 'Oklahoma: Modified 50%'),
('slip_fall', 'OR', 270, 120, 420, 'industry_benchmark', 'Oregon: Modified 51%'),
('slip_fall', 'PA', 300, 150, 480, 'industry_benchmark', 'Pennsylvania: Hills and Ridges doctrine; busy Philadelphia docket'),
('slip_fall', 'RI', 270, 120, 420, 'industry_benchmark', 'Rhode Island: Pure comparative'),
('slip_fall', 'SC', 300, 150, 480, 'industry_benchmark', 'South Carolina: Mixed contributory/comparative'),
('slip_fall', 'SD', 270, 120, 420, 'industry_benchmark', 'South Dakota: Modified comparative'),
('slip_fall', 'TN', 210, 90, 360, 'industry_benchmark', 'Tennessee: 1-year SOL creates urgency; modified 50% bar'),
('slip_fall', 'TX', 240, 120, 360, 'industry_benchmark', 'Texas: High volume; strict notice requirements'),
('slip_fall', 'UT', 240, 120, 360, 'industry_benchmark', 'Utah: Modified 50%'),
('slip_fall', 'VT', 300, 150, 450, 'industry_benchmark', 'Vermont: Pure comparative; rural jurisdiction'),
('slip_fall', 'VA', 300, 150, 480, 'industry_benchmark', 'Virginia: Contributory negligence'),
('slip_fall', 'WA', 270, 120, 420, 'industry_benchmark', 'Washington: Pure comparative; several liability'),
('slip_fall', 'WV', 270, 120, 420, 'industry_benchmark', 'West Virginia: Modified 51%'),
('slip_fall', 'WI', 270, 120, 420, 'industry_benchmark', 'Wisconsin: Safe Place Statute; modified 51%'),
('slip_fall', 'WY', 270, 120, 420, 'industry_benchmark', 'Wyoming: Modified 50%'),

-- Auto Accident (general defaults; state-specific adjustments where notable)
('auto_accident', 'AL', 240, 120, 420, 'industry_benchmark', 'Contributory; fewer cases proceed'),
('auto_accident', 'AZ', 210, 90, 360, 'industry_benchmark', 'Modified comparative'),
('auto_accident', 'CA', 270, 120, 480, 'industry_benchmark', 'Pure comparative; high volume; longer timelines'),
('auto_accident', 'FL', 180, 90, 300, 'industry_benchmark', 'High volume; insurers settle faster post-reform'),
('auto_accident', 'GA', 240, 120, 360, 'industry_benchmark', 'Modified 50% bar'),
('auto_accident', 'IL', 240, 120, 420, 'industry_benchmark', 'Cook County slow'),
('auto_accident', 'LA', 180, 90, 300, 'industry_benchmark', '1-year SOL; fastest'),
('auto_accident', 'MI', 240, 120, 360, 'industry_benchmark', 'No-fault threshold for auto'),
('auto_accident', 'NJ', 270, 120, 420, 'industry_benchmark', 'Busy courts'),
('auto_accident', 'NY', 300, 150, 540, 'industry_benchmark', 'No-fault state; long litigation timelines'),
('auto_accident', 'PA', 270, 120, 420, 'industry_benchmark', 'Limited tort option affects timeline'),
('auto_accident', 'TX', 210, 90, 360, 'industry_benchmark', 'High volume; moderate pace'),
('auto_accident', 'TN', 180, 90, 300, 'industry_benchmark', '1-year SOL'),

-- Dog Bite (generally faster settlement; strict liability in many states)
('dog_bite', 'CA', 180, 90, 300, 'industry_benchmark', 'Strict liability; Civil Code 3342'),
('dog_bite', 'FL', 150, 60, 270, 'industry_benchmark', 'Strict liability; F.S. 767.04'),
('dog_bite', 'NY', 210, 90, 360, 'industry_benchmark', 'Mixed strict/negligence; busy courts'),
('dog_bite', 'TX', 180, 90, 300, 'industry_benchmark', 'One-bite rule; negligence-based'),
('dog_bite', 'PA', 180, 90, 300, 'industry_benchmark', 'Strict liability 3 P.S. § 459-556'),

-- General PI (fallback for incident types without specific windows)
('general_pi', 'AL', 270, 120, 420, 'industry_benchmark', 'Contributory; fallback'),
('general_pi', 'AK', 300, 150, 450, 'industry_benchmark', 'Pure comparative; fallback'),
('general_pi', 'AZ', 240, 120, 360, 'industry_benchmark', 'Modified 51%; fallback'),
('general_pi', 'AR', 270, 120, 420, 'industry_benchmark', 'Modified 50%; fallback'),
('general_pi', 'CA', 300, 150, 540, 'industry_benchmark', 'Pure comparative; fallback'),
('general_pi', 'CO', 270, 120, 420, 'industry_benchmark', 'Modified 51%; fallback'),
('general_pi', 'CT', 270, 120, 420, 'industry_benchmark', 'Modified 51%; fallback'),
('general_pi', 'DE', 240, 120, 360, 'industry_benchmark', 'Modified 50%; fallback'),
('general_pi', 'FL', 240, 120, 420, 'industry_benchmark', 'Modified 51%; fallback'),
('general_pi', 'GA', 270, 120, 420, 'industry_benchmark', 'Modified 50%; fallback'),
('general_pi', 'HI', 300, 150, 450, 'industry_benchmark', 'Modified 51%; fallback'),
('general_pi', 'ID', 240, 120, 360, 'industry_benchmark', 'Modified 50%; fallback'),
('general_pi', 'IL', 270, 120, 420, 'industry_benchmark', 'Modified 51%; fallback'),
('general_pi', 'IN', 240, 120, 360, 'industry_benchmark', 'Modified 51%; fallback'),
('general_pi', 'IA', 270, 120, 420, 'industry_benchmark', 'Modified 51%; fallback'),
('general_pi', 'KS', 240, 120, 360, 'industry_benchmark', 'Modified 50%; fallback'),
('general_pi', 'KY', 240, 90, 390, 'industry_benchmark', '1-year SOL urgency; fallback'),
('general_pi', 'LA', 180, 90, 300, 'industry_benchmark', '1-year SOL; fastest; fallback'),
('general_pi', 'ME', 300, 150, 540, 'industry_benchmark', '6-year SOL; no urgency; fallback'),
('general_pi', 'MD', 300, 150, 480, 'industry_benchmark', 'Contributory; fallback'),
('general_pi', 'MA', 270, 120, 420, 'industry_benchmark', 'Modified 51%; fallback'),
('general_pi', 'MI', 270, 120, 420, 'industry_benchmark', 'Modified 51%; fallback'),
('general_pi', 'MN', 270, 120, 420, 'industry_benchmark', 'Modified 50%; fallback'),
('general_pi', 'MS', 300, 150, 480, 'industry_benchmark', 'Modified 51%; fallback'),
('general_pi', 'MO', 270, 120, 420, 'industry_benchmark', 'Modified comparative; fallback'),
('general_pi', 'MT', 300, 150, 450, 'industry_benchmark', 'Modified 51%; fallback'),
('general_pi', 'NE', 270, 120, 420, 'industry_benchmark', 'Modified 51%; fallback'),
('general_pi', 'NV', 270, 120, 420, 'industry_benchmark', 'Modified 51%; fallback'),
('general_pi', 'NH', 270, 120, 420, 'industry_benchmark', 'Modified 51%; fallback'),
('general_pi', 'NJ', 300, 150, 480, 'industry_benchmark', 'Modified 51%; fallback'),
('general_pi', 'NM', 270, 120, 420, 'industry_benchmark', 'Pure comparative; fallback'),
('general_pi', 'NY', 330, 180, 540, 'industry_benchmark', 'Busy courts; longest; fallback'),
('general_pi', 'NC', 300, 150, 480, 'industry_benchmark', 'Contributory; fallback'),
('general_pi', 'ND', 270, 120, 420, 'industry_benchmark', 'Modified 50%; fallback'),
('general_pi', 'OH', 270, 120, 420, 'industry_benchmark', 'Modified 51%; fallback'),
('general_pi', 'OK', 270, 120, 420, 'industry_benchmark', 'Modified 50%; fallback'),
('general_pi', 'OR', 270, 120, 420, 'industry_benchmark', 'Modified 51%; fallback'),
('general_pi', 'PA', 300, 150, 480, 'industry_benchmark', 'Modified 51%; fallback'),
('general_pi', 'RI', 270, 120, 420, 'industry_benchmark', 'Pure comparative; fallback'),
('general_pi', 'SC', 300, 150, 480, 'industry_benchmark', 'Mixed; fallback'),
('general_pi', 'SD', 270, 120, 420, 'industry_benchmark', 'Modified comparative; fallback'),
('general_pi', 'TN', 210, 90, 360, 'industry_benchmark', '1-year SOL; fallback'),
('general_pi', 'TX', 240, 120, 360, 'industry_benchmark', 'Modified 51%; fallback'),
('general_pi', 'UT', 240, 120, 360, 'industry_benchmark', 'Modified 50%; fallback'),
('general_pi', 'VT', 300, 150, 450, 'industry_benchmark', 'Pure comparative; fallback'),
('general_pi', 'VA', 300, 150, 480, 'industry_benchmark', 'Contributory; fallback'),
('general_pi', 'WA', 270, 120, 420, 'industry_benchmark', 'Pure comparative; fallback'),
('general_pi', 'WV', 270, 120, 420, 'industry_benchmark', 'Modified 51%; fallback'),
('general_pi', 'WI', 270, 120, 420, 'industry_benchmark', 'Modified 51%; fallback'),
('general_pi', 'WY', 270, 120, 420, 'industry_benchmark', 'Modified 50%; fallback')
ON CONFLICT (incident_type, state) DO UPDATE SET
    estimated_days_to_settle = EXCLUDED.estimated_days_to_settle,
    p25_days = EXCLUDED.p25_days,
    p75_days = EXCLUDED.p75_days,
    source = EXCLUDED.source,
    notes = EXCLUDED.notes,
    updated_at = now();
