-- =====================================================
-- California (CA) Medical Malpractice Rules
-- Enhanced Verification Protocol v2.0
-- =====================================================
-- State: California
-- Governing Law: MICRA (Medical Injury Compensation Reform Act), CCP § 340.5, Civ. Code § 3333.2
-- Negligence Model: PURE COMPARATIVE FAULT (Li v. Yellow Cab Co., 13 Cal.3d 804 (1975))
-- SOL: 3 years from injury OR 1 year from discovery — whichever is EARLIER (CCP § 340.5)
-- Non-Economic Cap: $350,000 (AB 35, effective Jan 1 2023); rising $40K/yr to $750K by 2033
-- Wrongful Death Cap: $500,000 (rising $50K/yr to $1M by 2033)
-- Pre-suit Notice: 90 days written notice to defendant required (CCP § 364)
-- Attorney Fees: Sliding scale limitation (Civ. Code § 6146)
-- =====================================================

-- RULE 1: STANDARD OF CARE
INSERT INTO leverage.validation_rules (rule_name, validator_level, validator_name, validator_type, practice_area, specialization, document_type, jurisdiction_scope, jurisdiction_state, validator_config, severity, review_status, is_active, is_template, created_at, updated_at)
VALUES ('CA-MED-MAL-STANDARD-OF-CARE', 5, 'CA Medical Malpractice: Standard of Care (MICRA / Common Law)', 'content_check', 'personal_injury', 'medical_malpractice', 'complaint', 'state', 'CA',
    jsonb_build_object('sub_specialization_type', 'medical_malpractice', 'authority_level', 'contextual_rule', 'standard_text', 'A healthcare provider must use the degree of skill, knowledge, and care ordinarily possessed and exercised by members of the profession in good standing in the same or similar locality', 'key_elements', jsonb_build_array('Duty: provider-patient relationship established', 'Breach: failure to meet the standard of care', 'Causation: breach was a substantial factor in causing the injury', 'Damages: actual harm resulted'), 'locality_rule', 'California applies a modified locality rule — standard of care for general practitioners is measured in same or similar locality; specialists are held to a national standard', 'res_ipsa', 'Available under specific circumstances where injury would not ordinarily occur without negligence and the instrumentality was in defendant control (CACI 513)', 'informed_consent', 'Separate claim under Cobbs v. Grant, 8 Cal.3d 229 (1972); provider must disclose risks a reasonable patient would want to know — objective reasonable patient standard', 'hospital_liability', 'Hospitals liable for non-delegable duties and under ostensible agency for physicians without clear disclosure of independent contractor status', 'verification', jsonb_build_object('statute_verified', true, 'sources', jsonb_build_array('MICRA — California Medical Injury Compensation Reform Act', 'CACI 500 et seq.', 'Cobbs v. Grant, 8 Cal.3d 229 (1972)', 'Justia — California Medical Malpractice'), 'confidence', 'high')),
    'error', 'document_verified', true, false, NOW(), NOW())
ON CONFLICT (rule_name) DO UPDATE SET validator_config = EXCLUDED.validator_config, updated_at = NOW();

-- RULE 2: EXPERT WITNESS AND PRE-SUIT NOTICE
INSERT INTO leverage.validation_rules (rule_name, validator_level, validator_name, validator_type, practice_area, specialization, document_type, jurisdiction_scope, jurisdiction_state, validator_config, severity, review_status, is_active, is_template, created_at, updated_at)
VALUES ('CA-MED-MAL-PRE-SUIT-NOTICE', 5, 'CA Medical Malpractice: 90-Day Pre-Suit Notice Required (CCP § 364)', 'content_check', 'personal_injury', 'medical_malpractice', 'complaint', 'state', 'CA',
    jsonb_build_object('sub_specialization_type', 'medical_malpractice', 'authority_level', 'contextual_rule', 'statute', 'CCP § 364', 'requirement', 'MANDATORY — Plaintiff must provide at least 90 days written notice to the defendant healthcare provider BEFORE filing a medical malpractice lawsuit', 'notice_contents', jsonb_build_object('who', 'Must be provided to each defendant healthcare provider named in the intended suit', 'what', 'Written notice specifying: the legal basis for the claim, the type of loss incurred, and the nature of the injuries suffered'), 'sol_tolling', 'If notice is given within 90 days of the SOL deadline, the SOL is extended by 90 days from the date of notice', 'failure_to_give_notice', 'Failure to give proper notice does not deprive court of jurisdiction but gives defendant ground to challenge', 'expert_requirement', 'Expert testimony required at trial to prove standard of care and breach; no statutory pre-filing affidavit required in California', 'expert_qualifications', 'Expert must be licensed healthcare provider in same or related specialty; must be familiar with standard of care applicable at time and in relevant locality', 'attorney_fees', jsonb_build_object('statute', 'Civ. Code § 6146', 'rule', 'Attorney fees in medical malpractice cases are limited to a sliding scale: 40% of first $50K, 33.3% of next $50K, 25% of next $500K, 15% of amounts over $600K'), 'verification', jsonb_build_object('statute_verified', true, 'sources', jsonb_build_array('CCP § 364', 'Civ. Code § 6146', 'California Legislature', 'Justia — California CCP § 364'), 'confidence', 'high')),
    'error', 'document_verified', true, false, NOW(), NOW())
ON CONFLICT (rule_name) DO UPDATE SET validator_config = EXCLUDED.validator_config, updated_at = NOW();

-- RULE 3: MICRA DAMAGE CAPS
INSERT INTO leverage.validation_rules (rule_name, validator_level, validator_name, validator_type, practice_area, specialization, document_type, jurisdiction_scope, jurisdiction_state, validator_config, severity, review_status, is_active, is_template, created_at, updated_at)
VALUES ('CA-MED-MAL-MICRA-DAMAGE-CAPS', 5, 'CA Medical Malpractice: MICRA Non-Economic Cap $350K (Civ. Code § 3333.2, AB 35)', 'content_check', 'personal_injury', 'medical_malpractice', 'complaint', 'state', 'CA',
    jsonb_build_object('sub_specialization_type', 'medical_malpractice', 'authority_level', 'contextual_rule', 'statute', 'Civ. Code § 3333.2 (MICRA)', 'economic_damages', 'UNCAPPED — full recovery of all economic losses (medical expenses, lost earnings, future care, rehabilitation)', 'non_economic_damages', jsonb_build_object('original_cap', '$250,000 (1975–2022)', 'current_cap_2023', '$350,000 — effective January 1, 2023 (AB 35)', 'annual_increases', 'Cap increases $40,000/year until reaching $750,000 in 2033, then indexed to inflation', 'cap_schedule', jsonb_build_object('2023', '$350,000', '2024', '$390,000', '2025', '$430,000', '2026', '$470,000', '2033_and_beyond', '$750,000 then CPI-indexed'), 'applies_to', 'Pain and suffering, mental anguish, loss of consortium, disfigurement, loss of enjoyment of life'), 'wrongful_death', jsonb_build_object('cap_2023', '$500,000', 'annual_increases', 'Cap increases $50,000/year until reaching $1,000,000 in 2033, then inflation-indexed', 'cap_2026', '$650,000'), 'cap_per_case', 'Cap applies per plaintiff regardless of number of defendant providers', 'punitive_damages', jsonb_build_object('availability', 'Limited under MICRA — must show clear and convincing evidence of oppression, fraud, or malice', 'not_subject_to_micra_cap', 'Punitive damages are NOT subject to the non-economic damage cap'), 'collateral_source', 'California allows defendants to present evidence of collateral source payments to reduce economic damage awards (Civ. Code § 3333.1)', 'verification', jsonb_build_object('statute_verified', true, 'sources', jsonb_build_array('Civ. Code § 3333.2', 'AB 35 (2022)', 'Civ. Code § 3333.1', 'California Legislature', 'Justia — California MICRA'), 'confidence', 'high')),
    'error', 'document_verified', true, false, NOW(), NOW())
ON CONFLICT (rule_name) DO UPDATE SET validator_config = EXCLUDED.validator_config, updated_at = NOW();

-- RULE 4: STATUTE OF LIMITATIONS
INSERT INTO leverage.validation_rules (rule_name, validator_level, validator_name, validator_type, practice_area, specialization, document_type, jurisdiction_scope, jurisdiction_state, validator_config, severity, review_status, is_active, is_template, created_at, updated_at)
VALUES ('CA-MED-MAL-SOL-3-YEARS', 5, 'CA Medical Malpractice: 3-Year/1-Year SOL — Whichever Earlier (CCP § 340.5)', 'content_check', 'personal_injury', 'medical_malpractice', 'complaint', 'state', 'CA',
    jsonb_build_object('sub_specialization_type', 'medical_malpractice', 'authority_level', 'contextual_rule', 'statute', 'CCP § 340.5', 'sol_rule', 'EARLIER of: (1) 3 years from the date of injury, OR (2) 1 year from the date the plaintiff discovered or should have discovered the injury', 'statute_text', 'CCP § 340.5: An action for injury or death against a health care provider shall be commenced within three years after the date of injury or one year after the plaintiff discovers, or through the use of reasonable diligence should have discovered, the injury, whichever occurs first', 'three_year_rule', 'Outer limit: 3 years from actual injury date regardless of discovery — this is the statute of repose', 'one_year_discovery', 'Inner limit: 1 year from date plaintiff actually discovered (or reasonably should have discovered) the injury AND its negligent cause', 'which_governs', 'File whichever deadline expires FIRST — most plaintiffs face the 1-year discovery rule as the tighter deadline', 'fraud_exception', 'SOL tolled where defendant fraudulently concealed the malpractice; clock does not start until concealment is discovered', 'foreign_object', 'Foreign object left in body: 1 year from discovery of foreign object (within 3-year outer limit)', 'minors', 'For minors: SOL is 3 years OR until 8th birthday, whichever is LONGER', 'pre_suit_notice_effect', 'Providing 90-day CCP § 364 pre-suit notice within 90 days before SOL expiration extends the SOL by 90 days from date of notice', 'tolling', jsonb_build_array('Fraudulent concealment', 'Minority (extended to age 8 or 3 years from injury)', 'Continuous treatment (some circumstances)', 'CCP § 364 pre-suit notice (tolls by 90 days)'), 'practical_examples', jsonb_build_array('Surgery Jan 1 2024, discovered negligence Mar 1 2024 → File by Mar 1 2025 (1-yr discovery)', 'Surgery Jan 1 2024, never specifically discovered → File by Jan 1 2027 (3-yr outer limit)'), 'verification', jsonb_build_object('statute_verified', true, 'sources', jsonb_build_array('CCP § 340.5', 'California Legislature', 'Fogarty v. Superior Court, 117 Cal.App.3d 316 (1981)', 'Justia — CCP 340.5'), 'confidence', 'high')),
    'error', 'document_verified', true, false, NOW(), NOW())
ON CONFLICT (rule_name) DO UPDATE SET validator_config = EXCLUDED.validator_config, updated_at = NOW();

-- RULE 5: PURE COMPARATIVE FAULT
INSERT INTO leverage.validation_rules (rule_name, validator_level, validator_name, validator_type, practice_area, specialization, document_type, jurisdiction_scope, jurisdiction_state, validator_config, severity, review_status, is_active, is_template, created_at, updated_at)
VALUES ('CA-MED-MAL-PURE-COMPARATIVE-FAULT', 5, 'CA Medical Malpractice: Pure Comparative Fault (Li v. Yellow Cab / CCP § 1431.2)', 'content_check', 'personal_injury', 'medical_malpractice', 'complaint', 'state', 'CA',
    jsonb_build_object('sub_specialization_type', 'medical_malpractice', 'authority_level', 'contextual_rule', 'case_law', 'Li v. Yellow Cab Co., 13 Cal.3d 804 (1975)', 'statute', 'CCP § 1431.2 (several liability for non-economic damages)', 'negligence_model', 'pure_comparative_fault', 'rule', 'Plaintiff can recover even if 99% at fault; damages reduced proportionally by plaintiff fault percentage', 'patient_contributory_conduct', 'Patient failure to follow medical orders, delayed seeking care, or failure to disclose relevant history reduces recovery proportionally', 'economic_damages_liability', 'Each defendant jointly and severally liable for all economic damages (medical bills, lost wages)', 'non_economic_damages_liability', 'Each defendant SEVERALLY LIABLE ONLY for non-economic damages — pays only their proportionate share (CCP § 1431.2)', 'practical_examples', jsonb_build_array('Plaintiff 0% at fault: Full recovery of all damages', 'Plaintiff 20% at fault: Economic damages fully recoverable from any defendant; non-economic reduced by 20%', 'Plaintiff 99% at fault: Can still recover 1% of damages'), 'multiple_defendants', 'Joint and several for economic damages; several only for non-economic damages per Proposition 51 (1986)', 'verification', jsonb_build_object('statute_verified', true, 'sources', jsonb_build_array('Li v. Yellow Cab Co., 13 Cal.3d 804 (1975)', 'CCP § 1431.2', 'California Proposition 51 (1986)', 'California Legislature'), 'confidence', 'high')),
    'error', 'document_verified', true, false, NOW(), NOW())
ON CONFLICT (rule_name) DO UPDATE SET validator_config = EXCLUDED.validator_config, updated_at = NOW();
