-- =====================================================
-- Georgia (GA) Medical Malpractice Rules
-- Enhanced Verification Protocol v2.0
-- =====================================================
-- State: Georgia
-- Governing Law: OCGA § 9-3-70 et seq., § 51-1-27
-- Negligence Model: MODIFIED COMPARATIVE FAULT — 50% bar (OCGA § 51-12-33)
-- SOL: 2 years from injury (OCGA § 9-3-71); 5-year statute of repose
-- Damage Caps: Non-economic $350K cap (OCGA § 51-13-1) STRUCK DOWN as unconstitutional (2010)
-- Affidavit of Merit: MANDATORY — must accompany complaint (OCGA § 9-11-9.1)
-- Punitive: $250,000 cap (OCGA § 51-12-5.1)
-- =====================================================

-- RULE 1: STANDARD OF CARE
INSERT INTO leverage.validation_rules (rule_name, validator_level, validator_name, validator_type, practice_area, specialization, document_type, jurisdiction_scope, jurisdiction_state, validator_config, severity, review_status, is_active, is_template, created_at, updated_at)
VALUES ('GA-MED-MAL-STANDARD-OF-CARE', 5, 'GA Medical Malpractice: Standard of Care (OCGA § 51-1-27)', 'content_check', 'personal_injury', 'medical_malpractice', 'complaint', 'state', 'GA',
    jsonb_build_object('sub_specialization_type', 'medical_malpractice', 'authority_level', 'contextual_rule', 'statute', 'OCGA § 51-1-27', 'standard_text', 'Medical professionals must exercise a reasonable degree of care, skill, and treatment which, in light of all relevant surrounding circumstances, is recognized as acceptable and appropriate by reasonably prudent similar health care providers', 'key_elements', jsonb_build_array('Duty: provider-patient relationship established', 'Breach: failure to exercise reasonable care and skill', 'Causation: breach proximately caused injury', 'Damages: actual compensable harm'), 'national_standard', 'Georgia generally applies a national standard for specialists; general practitioners held to general community standard', 'res_ipsa', 'Available in limited circumstances — foreign object left in body, wrong body part operated on', 'informed_consent', 'Separate theory under OCGA § 31-9-6.1: provider must disclose material risks; specific procedures require written consent', 'hospital_liability', 'Hospitals may be directly liable for negligent credentialing and vicariously liable for employed physicians', 'verification', jsonb_build_object('statute_verified', true, 'sources', jsonb_build_array('OCGA § 51-1-27', 'Georgia Code Title 51', 'Justia — Georgia Medical Malpractice'), 'confidence', 'high')),
    'error', 'document_verified', true, false, NOW(), NOW())
ON CONFLICT (rule_name) DO UPDATE SET validator_config = EXCLUDED.validator_config, updated_at = NOW();

-- RULE 2: AFFIDAVIT OF MERIT (MANDATORY)
INSERT INTO leverage.validation_rules (rule_name, validator_level, validator_name, validator_type, practice_area, specialization, document_type, jurisdiction_scope, jurisdiction_state, validator_config, severity, review_status, is_active, is_template, created_at, updated_at)
VALUES ('GA-MED-MAL-AFFIDAVIT-OF-MERIT', 5, 'GA Medical Malpractice: Expert Affidavit MANDATORY at Filing (OCGA § 9-11-9.1)', 'content_check', 'personal_injury', 'medical_malpractice', 'complaint', 'state', 'GA',
    jsonb_build_object('sub_specialization_type', 'medical_malpractice', 'authority_level', 'contextual_rule', 'statute', 'OCGA § 9-11-9.1', 'requirement', 'MANDATORY — Expert affidavit must accompany the complaint in every medical malpractice action', 'affidavit_contents', jsonb_build_object('at_least_one_act', 'Affidavit must specifically identify at least one negligent act or omission claimed to have occurred in the provision of professional services', 'basis', 'Must be based on the expert''s review of the facts, experience, and knowledge of the applicable standards of care'), 'expert_qualifications', jsonb_build_object('same_specialty', 'Expert must be competent to testify under OCGA § 24-7-702 — licensed in same specialty as defendant', 'recent_practice', 'Must have practiced in same specialty during the year preceding the alleged malpractice'), 'sol_emergency_exception', 'SOL emergency exception: If retained less than 90 days before SOL expiration, attorney may file sworn statement and has 45 days to file affidavit after complaint', 'failure_to_comply', 'Failure to file proper expert affidavit is grounds for dismissal of the action', 'verification', jsonb_build_object('statute_verified', true, 'sources', jsonb_build_array('OCGA § 9-11-9.1', 'OCGA § 24-7-702', 'Georgia Legislature', 'Justia — Georgia OCGA 9-11-9.1'), 'confidence', 'high')),
    'error', 'document_verified', true, false, NOW(), NOW())
ON CONFLICT (rule_name) DO UPDATE SET validator_config = EXCLUDED.validator_config, updated_at = NOW();

-- RULE 3: DAMAGE CAPS
INSERT INTO leverage.validation_rules (rule_name, validator_level, validator_name, validator_type, practice_area, specialization, document_type, jurisdiction_scope, jurisdiction_state, validator_config, severity, review_status, is_active, is_template, created_at, updated_at)
VALUES ('GA-MED-MAL-DAMAGE-CAPS', 5, 'GA Medical Malpractice: Non-Economic Cap STRUCK DOWN; Punitive $250K Cap (OCGA § 51-13-1)', 'content_check', 'personal_injury', 'medical_malpractice', 'complaint', 'state', 'GA',
    jsonb_build_object('sub_specialization_type', 'medical_malpractice', 'authority_level', 'contextual_rule', 'economic_damages', 'UNCAPPED — full recovery of all verifiable economic losses (medical bills, lost wages, future care)', 'non_economic_damages', jsonb_build_object('statutory_cap', '$350,000 cap was enacted in OCGA § 51-13-1', 'cap_status', 'STRUCK DOWN as unconstitutional by Georgia Supreme Court in Atlanta Oculoplastic Surgery, P.C. v. Nestlehutt, 286 Ga. 218 (2010) — violated right to jury trial under Georgia Constitution', 'current_status', 'NO EFFECTIVE non-economic damage cap in Georgia medical malpractice cases', 'full_jury_determination', 'Jury has full discretion to award non-economic damages'), 'punitive_damages', jsonb_build_object('statute', 'OCGA § 51-12-5.1', 'cap', '$250,000 cap on punitive damages in most cases', 'exception', 'No cap for cases of intentional harm, product liability, or driving under the influence', 'standard', 'Must show clear and convincing evidence of willful misconduct, malice, fraud, wantonness, or entire want of care'), 'collateral_source', 'Georgia follows traditional collateral source rule — collateral source payments do not reduce plaintiff damages', 'verification', jsonb_build_object('statute_verified', true, 'sources', jsonb_build_array('OCGA § 51-13-1 (struck down)', 'OCGA § 51-12-5.1', 'Atlanta Oculoplastic Surgery v. Nestlehutt, 286 Ga. 218 (2010)', 'Georgia Legislature'), 'confidence', 'high')),
    'error', 'document_verified', true, false, NOW(), NOW())
ON CONFLICT (rule_name) DO UPDATE SET validator_config = EXCLUDED.validator_config, updated_at = NOW();

-- RULE 4: STATUTE OF LIMITATIONS
INSERT INTO leverage.validation_rules (rule_name, validator_level, validator_name, validator_type, practice_area, specialization, document_type, jurisdiction_scope, jurisdiction_state, validator_config, severity, review_status, is_active, is_template, created_at, updated_at)
VALUES ('GA-MED-MAL-SOL-2-YEARS', 5, 'GA Medical Malpractice: 2-Year SOL with 5-Year Repose (OCGA § 9-3-71)', 'content_check', 'personal_injury', 'medical_malpractice', 'complaint', 'state', 'GA',
    jsonb_build_object('sub_specialization_type', 'medical_malpractice', 'authority_level', 'contextual_rule', 'statute', 'OCGA § 9-3-71', 'sol_period', '2 years', 'accrual', 'SOL begins on the date of the negligent act or omission', 'statute_text', 'OCGA § 9-3-71(a): An action for medical malpractice shall be brought within two years after the date on which an injury or death arising from a negligent or wrongful act or omission occurred', 'statute_of_repose', jsonb_build_object('period', '5 years', 'description', 'ABSOLUTE DEADLINE — no action more than 5 years after the negligent act regardless of discovery (OCGA § 9-3-71(b))', 'statute', 'OCGA § 9-3-71(b)'), 'foreign_object', 'Foreign object left in body: 1 year from date of discovery, but cannot exceed 5-year repose (OCGA § 9-3-72)', 'fraud_exception', 'Fraudulent concealment: tolls SOL until discovery, cannot exceed 10 years from date of act', 'minors', 'For children under 5: SOL runs until 2 years after child''s 5th birthday; children 5 and older subject to standard 2-year period (OCGA § 9-3-73)', 'tolling', jsonb_build_array('Minority (under 5 — special rule)', 'Fraudulent concealment (max 10 years from act)', 'Mental incapacity'), 'practical_examples', jsonb_build_array('Malpractice Jan 1 2024 → Must file by Jan 1 2026 (2-yr SOL)', 'Malpractice Jan 1 2024 → Absolute repose Jan 1 2029 (5-yr)'), 'verification', jsonb_build_object('statute_verified', true, 'sources', jsonb_build_array('OCGA § 9-3-71', 'OCGA § 9-3-72', 'OCGA § 9-3-73', 'Georgia Legislature', 'Justia — Georgia Medical Malpractice'), 'confidence', 'high')),
    'error', 'document_verified', true, false, NOW(), NOW())
ON CONFLICT (rule_name) DO UPDATE SET validator_config = EXCLUDED.validator_config, updated_at = NOW();

-- RULE 5: MODIFIED COMPARATIVE FAULT (50% BAR)
INSERT INTO leverage.validation_rules (rule_name, validator_level, validator_name, validator_type, practice_area, specialization, document_type, jurisdiction_scope, jurisdiction_state, validator_config, severity, review_status, is_active, is_template, created_at, updated_at)
VALUES ('GA-MED-MAL-MODIFIED-COMPARATIVE', 5, 'GA Medical Malpractice: Modified Comparative Fault 50% Bar (OCGA § 51-12-33)', 'content_check', 'personal_injury', 'medical_malpractice', 'complaint', 'state', 'GA',
    jsonb_build_object('sub_specialization_type', 'medical_malpractice', 'authority_level', 'contextual_rule', 'statute', 'OCGA § 51-12-33', 'negligence_model', 'modified_comparative_50_bar', 'rule', 'Plaintiff may recover if their fault is 50% or LESS; barred from all recovery if fault exceeds 50%', 'patient_non_compliance', 'Patient failure to follow medical instructions, disclose medical history, or seek timely care can be allocated as plaintiff fault reducing or barring recovery', 'several_only_liability', jsonb_build_object('rule', 'Georgia apportions fault among all parties; each defendant pays only their proportionate share', 'statute', 'OCGA § 51-12-33(b)'), 'practical_examples', jsonb_build_array('Plaintiff 0% fault: Full recovery', 'Plaintiff 30% fault: Recovery reduced by 30%', 'Plaintiff 50% fault: Recovery reduced by 50% — can still recover', 'Plaintiff 51% fault: NO RECOVERY'), 'verification', jsonb_build_object('statute_verified', true, 'sources', jsonb_build_array('OCGA § 51-12-33', 'Georgia Legislature', 'Justia — Georgia Comparative Fault'), 'confidence', 'high')),
    'error', 'document_verified', true, false, NOW(), NOW())
ON CONFLICT (rule_name) DO UPDATE SET validator_config = EXCLUDED.validator_config, updated_at = NOW();
