-- =====================================================
-- Connecticut (CT) Medical Malpractice Rules
-- Enhanced Verification Protocol v2.0
-- =====================================================
-- State: Connecticut
-- Governing Law: CGS § 52-184b et seq., § 52-190a, § 52-584
-- Negligence Model: MODIFIED COMPARATIVE FAULT — 51% bar (CGS § 52-572h)
-- SOL: 2 years from discovery; 3-year statute of repose (CGS § 52-584)
-- Damage Caps: NO statutory cap on non-economic damages in Connecticut
-- Expert Opinion Letter: MANDATORY — must accompany complaint (CGS § 52-190a)
-- =====================================================

-- RULE 1: STANDARD OF CARE
INSERT INTO leverage.validation_rules (rule_name, validator_level, validator_name, validator_type, practice_area, specialization, document_type, jurisdiction_scope, jurisdiction_state, validator_config, severity, review_status, is_active, is_template, created_at, updated_at)
VALUES ('CT-MED-MAL-STANDARD-OF-CARE', 5, 'CT Medical Malpractice: Standard of Care (CGS § 52-184c)', 'content_check', 'personal_injury', 'medical_malpractice', 'complaint', 'state', 'CT',
    jsonb_build_object('sub_specialization_type', 'medical_malpractice', 'authority_level', 'contextual_rule', 'statute', 'CGS § 52-184c', 'standard_text', 'The claimant must prove the defendant health care provider breached the prevailing professional standard of care — the level of care, skill, and treatment recognized as acceptable and appropriate by reasonably competent similar health care providers under comparable circumstances', 'key_elements', jsonb_build_array('Duty: provider-patient relationship established', 'Breach: deviation from prevailing professional standard of care', 'Causation: breach was substantial factor in causing injury', 'Damages: actual compensable harm'), 'similar_provider_standard', 'CGS § 52-184c uses a "similar health care provider" standard — expert must be certified in same specialty OR possess equivalent training within last 5 years', 'res_ipsa', 'Available in clear negligence cases; most malpractice cases require expert testimony', 'informed_consent', 'Separate claim: provider must disclose material risks a reasonable patient would want to know; objective reasonable patient standard', 'hospital_liability', 'Hospitals may be directly liable for negligent credentialing and vicariously liable for employees', 'verification', jsonb_build_object('statute_verified', true, 'sources', jsonb_build_array('CGS § 52-184c', 'Connecticut General Statutes', 'Justia — Connecticut Medical Malpractice'), 'confidence', 'high')),
    'error', 'document_verified', true, false, NOW(), NOW())
ON CONFLICT (rule_name) DO UPDATE SET validator_config = EXCLUDED.validator_config, updated_at = NOW();

-- RULE 2: EXPERT OPINION LETTER (MANDATORY)
INSERT INTO leverage.validation_rules (rule_name, validator_level, validator_name, validator_type, practice_area, specialization, document_type, jurisdiction_scope, jurisdiction_state, validator_config, severity, review_status, is_active, is_template, created_at, updated_at)
VALUES ('CT-MED-MAL-EXPERT-OPINION-LETTER', 5, 'CT Medical Malpractice: Expert Opinion Letter MANDATORY (CGS § 52-190a)', 'content_check', 'personal_injury', 'medical_malpractice', 'complaint', 'state', 'CT',
    jsonb_build_object('sub_specialization_type', 'medical_malpractice', 'authority_level', 'contextual_rule', 'statute', 'CGS § 52-190a', 'requirement', 'MANDATORY — Plaintiff must attach a written expert opinion letter to the complaint affirming there is evidence of medical negligence', 'expert_qualifications', jsonb_build_object('similar_provider', 'Expert must be a "similar health care provider" as defined in CGS § 52-184c', 'same_specialty', 'If defendant is a specialist: expert must be certified in same specialty OR have equivalent training and experience in last 5 years', 'general_practitioner', 'If defendant is not a specialist: expert must be licensed in same field and actively practicing or teaching'), 'opinion_contents', 'Letter must state there is evidence that the defendant deviated from the applicable standard of care and this deviation caused the claimant injury', 'sol_extension', '90-day extension of SOL available to conduct reasonable investigation before filing (CGS § 52-190a(b))', 'carpenter_ruling', 'CT Supreme Court in Carpenter v. Daar (2023): insufficient opinion letter does not automatically require dismissal; court may allow amendment/supplementation', 'failure_consequences', 'Failure to provide proper opinion letter may lead to dismissal — but see Carpenter v. Daar (2023) for judicial flexibility', 'verification', jsonb_build_object('statute_verified', true, 'sources', jsonb_build_array('CGS § 52-190a', 'CGS § 52-184c', 'Carpenter v. Daar, 346 Conn. 278 (2023)', 'Justia — Connecticut CGS 52-190a'), 'confidence', 'high')),
    'error', 'document_verified', true, false, NOW(), NOW())
ON CONFLICT (rule_name) DO UPDATE SET validator_config = EXCLUDED.validator_config, updated_at = NOW();

-- RULE 3: NO DAMAGE CAPS
INSERT INTO leverage.validation_rules (rule_name, validator_level, validator_name, validator_type, practice_area, specialization, document_type, jurisdiction_scope, jurisdiction_state, validator_config, severity, review_status, is_active, is_template, created_at, updated_at)
VALUES ('CT-MED-MAL-NO-DAMAGE-CAPS', 5, 'CT Medical Malpractice: NO Statutory Damage Caps', 'content_check', 'personal_injury', 'medical_malpractice', 'complaint', 'state', 'CT',
    jsonb_build_object('sub_specialization_type', 'medical_malpractice', 'authority_level', 'contextual_rule', 'economic_damages', 'UNCAPPED — full recovery of all verifiable economic losses (medical bills, lost wages, future care)', 'non_economic_damages', jsonb_build_object('cap_status', 'NO CAP — Connecticut has no statutory cap on non-economic damages in medical malpractice cases', 'full_jury_determination', 'Jury has full discretion to award non-economic damages based on the evidence'), 'punitive_damages', jsonb_build_object('availability', 'Available in cases of wanton, willful, or malicious conduct', 'limitation', 'Punitive damages in Connecticut are generally limited to attorney fees and litigation costs rather than unlimited punitive award'), 'collateral_source', 'Connecticut generally follows traditional collateral source rule — collateral source payments do not reduce damages', 'periodic_payments', 'Connecticut allows future damages to be paid in periodic payments rather than lump sum at court discretion', 'significant_note', 'Connecticut is a plaintiff-friendly state for damages — no non-economic cap and full collateral source protection', 'verification', jsonb_build_object('sources', jsonb_build_array('Connecticut General Statutes Title 52', 'Justia — Connecticut Medical Malpractice', 'NCSL Medical Malpractice Summary'), 'confidence', 'high')),
    'error', 'document_verified', true, false, NOW(), NOW())
ON CONFLICT (rule_name) DO UPDATE SET validator_config = EXCLUDED.validator_config, updated_at = NOW();

-- RULE 4: STATUTE OF LIMITATIONS
INSERT INTO leverage.validation_rules (rule_name, validator_level, validator_name, validator_type, practice_area, specialization, document_type, jurisdiction_scope, jurisdiction_state, validator_config, severity, review_status, is_active, is_template, created_at, updated_at)
VALUES ('CT-MED-MAL-SOL-2-YEARS', 5, 'CT Medical Malpractice: 2-Year SOL with 3-Year Repose (CGS § 52-584)', 'content_check', 'personal_injury', 'medical_malpractice', 'complaint', 'state', 'CT',
    jsonb_build_object('sub_specialization_type', 'medical_malpractice', 'authority_level', 'contextual_rule', 'statute', 'CGS § 52-584', 'sol_period', '2 years', 'accrual', 'SOL begins from the date the injury is first sustained or discovered, or when it should have been discovered with reasonable care', 'statute_text', 'CGS § 52-584: No action for personal injuries shall be brought but within two years from the date when the injury is first sustained or discovered or in the exercise of reasonable care should have been discovered...', 'statute_of_repose', jsonb_build_object('period', '3 years', 'description', 'ABSOLUTE DEADLINE — no action can be filed more than 3 years after the act or omission complained of regardless of discovery', 'note', '90-day SOL extension tolls the limitations period when plaintiff exercises right to investigate under CGS § 52-190a'), 'continuous_treatment', 'SOL does not begin until the course of treatment for the condition is completed (continuous treatment doctrine recognized in Connecticut)', 'foreign_object', 'Foreign object left in body: discovery rule applies within 2-year SOL', 'sol_extension', '90-day automatic extension available when plaintiff files written notice under CGS § 52-190a to conduct reasonable investigation', 'minors', 'For minors: SOL tolled until age 18, then standard periods apply', 'tolling', jsonb_build_array('Minority (under 18)', 'Fraudulent concealment', 'Continuous treatment doctrine', '90-day extension under CGS § 52-190a'), 'practical_examples', jsonb_build_array('Malpractice Jan 1 2024 discovered same day → File by Jan 1 2026', 'Malpractice Jan 1 2024 absolute repose → Jan 1 2027'), 'verification', jsonb_build_object('statute_verified', true, 'sources', jsonb_build_array('CGS § 52-584', 'CGS § 52-190a', 'Connecticut Legislature', 'Justia — Connecticut CGS 52-584'), 'confidence', 'high')),
    'error', 'document_verified', true, false, NOW(), NOW())
ON CONFLICT (rule_name) DO UPDATE SET validator_config = EXCLUDED.validator_config, updated_at = NOW();

-- RULE 5: MODIFIED COMPARATIVE FAULT (51% BAR)
INSERT INTO leverage.validation_rules (rule_name, validator_level, validator_name, validator_type, practice_area, specialization, document_type, jurisdiction_scope, jurisdiction_state, validator_config, severity, review_status, is_active, is_template, created_at, updated_at)
VALUES ('CT-MED-MAL-MODIFIED-COMPARATIVE', 5, 'CT Medical Malpractice: Modified Comparative Fault 51% Bar (CGS § 52-572h)', 'content_check', 'personal_injury', 'medical_malpractice', 'complaint', 'state', 'CT',
    jsonb_build_object('sub_specialization_type', 'medical_malpractice', 'authority_level', 'contextual_rule', 'statute', 'CGS § 52-572h', 'negligence_model', 'modified_comparative_51_bar', 'rule', 'Plaintiff may recover if their fault is 50% or LESS; barred from any recovery if fault is 51% or more', 'patient_non_compliance', 'Patient failure to follow medical instructions, provide accurate history, or seek follow-up care can be allocated as plaintiff fault', 'several_only_liability', jsonb_build_object('rule', 'Each defendant generally pays only their proportionate share of damages; joint and several liability limited (CGS § 52-572h(f))', 'statute', 'CGS § 52-572h(f)'), 'practical_examples', jsonb_build_array('Plaintiff 0% fault: Full recovery', 'Plaintiff 30% fault: Recovery reduced by 30%', 'Plaintiff 50% fault: Recovery reduced by 50% — can still recover', 'Plaintiff 51% fault: NO RECOVERY'), 'verification', jsonb_build_object('statute_verified', true, 'sources', jsonb_build_array('CGS § 52-572h', 'Connecticut Legislature', 'Justia — Connecticut Comparative Fault'), 'confidence', 'high')),
    'error', 'document_verified', true, false, NOW(), NOW())
ON CONFLICT (rule_name) DO UPDATE SET validator_config = EXCLUDED.validator_config, updated_at = NOW();
